// =====================
// Album Configuration with Full Photo Lists
// Generated by: scripts/generate-albums-data.js
// Total Images: 307
// Last Generated: 2026-02-03T22:00:57.013Z
// =====================

export interface AlbumImage {
  path: string;
  fileName: string;
  alt: string;
}

export interface AlbumConfig {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: string;
  coverImagePath: string | null;
  imageCount: number;
  images: AlbumImage[];
  isPrivate: boolean;
  createdAt: string;
}

// Get the full-size image URL (from backend)
export function getImageUrl(path: string): string {
  // Full images are served from backend
  const baseUrl = process.env.NEXT_PUBLIC_FULL_IMAGE_BASE_URL
    || process.env.NEXT_PUBLIC_API_BASE_URL + '/static/photos'
    || 'http://localhost:5000/static/photos';
  return `${baseUrl}${path.startsWith('/') ? path : '/' + path}`;
}

// Get thumbnail URL (from frontend public folder for fast loading)
export function getThumbnailUrl(path: string): string {
  // Thumbnails are served from frontend public folder (fast!)
  const thumbnailPath = path.replace(/\.(jpg|jpeg|png)$/i, '_thumb.jpg');
  const baseUrl = '/JourneyLifePhotos'; // Always use local for thumbnails
  return `${baseUrl}${thumbnailPath.startsWith('/') ? thumbnailPath : '/' + thumbnailPath}`;
}

export const albumsData: AlbumConfig[] = [
  {
    id: 'wedding-1',
    slug: 'wedding-1',
    title: 'Wedding 1',
    description: 'A beautiful wedding celebration captured in detail',
    category: 'Weddings',
    coverImagePath: '/Weddings/Wedding 1/small size/Album cover.jpg',
    imageCount: 31,
    images: [
      {
        path: '/Weddings/Wedding 1/small size/Album cover.jpg',
        fileName: 'Album cover.jpg',
        alt: 'Wedding 1 - Photo 1',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00215 - Copy.jpg',
        fileName: 'DSC00215 - Copy.jpg',
        alt: 'Wedding 1 - Photo 2',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00274.jpg',
        fileName: 'DSC00274.jpg',
        alt: 'Wedding 1 - Photo 3',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00425.jpg',
        fileName: 'DSC00425.jpg',
        alt: 'Wedding 1 - Photo 4',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00689.jpg',
        fileName: 'DSC00689.jpg',
        alt: 'Wedding 1 - Photo 5',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00739.jpg',
        fileName: 'DSC00739.jpg',
        alt: 'Wedding 1 - Photo 6',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00829.jpg',
        fileName: 'DSC00829.jpg',
        alt: 'Wedding 1 - Photo 7',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC01234.jpg',
        fileName: 'DSC01234.jpg',
        alt: 'Wedding 1 - Photo 8',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08036.jpg',
        fileName: 'DSC08036.jpg',
        alt: 'Wedding 1 - Photo 9',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08048-2.jpg',
        fileName: 'DSC08048-2.jpg',
        alt: 'Wedding 1 - Photo 10',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08076.jpg',
        fileName: 'DSC08076.jpg',
        alt: 'Wedding 1 - Photo 11',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08114 - Copy.jpg',
        fileName: 'DSC08114 - Copy.jpg',
        alt: 'Wedding 1 - Photo 12',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08160.jpg',
        fileName: 'DSC08160.jpg',
        alt: 'Wedding 1 - Photo 13',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08246 - Copy.jpg',
        fileName: 'DSC08246 - Copy.jpg',
        alt: 'Wedding 1 - Photo 14',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08341.jpg',
        fileName: 'DSC08341.jpg',
        alt: 'Wedding 1 - Photo 15',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08380.jpg',
        fileName: 'DSC08380.jpg',
        alt: 'Wedding 1 - Photo 16',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08421.jpg',
        fileName: 'DSC08421.jpg',
        alt: 'Wedding 1 - Photo 17',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08528.jpg',
        fileName: 'DSC08528.jpg',
        alt: 'Wedding 1 - Photo 18',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08607.jpg',
        fileName: 'DSC08607.jpg',
        alt: 'Wedding 1 - Photo 19',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08757.jpg',
        fileName: 'DSC08757.jpg',
        alt: 'Wedding 1 - Photo 20',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08789.jpg',
        fileName: 'DSC08789.jpg',
        alt: 'Wedding 1 - Photo 21',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08875.jpg',
        fileName: 'DSC08875.jpg',
        alt: 'Wedding 1 - Photo 22',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08922-2-Edit.jpg',
        fileName: 'DSC08922-2-Edit.jpg',
        alt: 'Wedding 1 - Photo 23',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08936-2.jpg',
        fileName: 'DSC08936-2.jpg',
        alt: 'Wedding 1 - Photo 24',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09025-2.jpg',
        fileName: 'DSC09025-2.jpg',
        alt: 'Wedding 1 - Photo 25',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09188-2.jpg',
        fileName: 'DSC09188-2.jpg',
        alt: 'Wedding 1 - Photo 26',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09224.jpg',
        fileName: 'DSC09224.jpg',
        alt: 'Wedding 1 - Photo 27',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09453.jpg',
        fileName: 'DSC09453.jpg',
        alt: 'Wedding 1 - Photo 28',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09613-Edit.jpg',
        fileName: 'DSC09613-Edit.jpg',
        alt: 'Wedding 1 - Photo 29',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09709.jpg',
        fileName: 'DSC09709.jpg',
        alt: 'Wedding 1 - Photo 30',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09791.jpg',
        fileName: 'DSC09791.jpg',
        alt: 'Wedding 1 - Photo 31',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-03',
  },

  {
    id: 'wedding-2',
    slug: 'wedding-2',
    title: 'Wedding 2',
    description: 'An elegant wedding ceremony and reception',
    category: 'Weddings',
    coverImagePath: '/Weddings/Wedding 2/Album cover 2.jpg',
    imageCount: 19,
    images: [
      {
        path: '/Weddings/Wedding 2/Album cover 2.jpg',
        fileName: 'Album cover 2.jpg',
        alt: 'Wedding 2 - Photo 1',
      },
      {
        path: '/Weddings/Wedding 2/DSC04955-Edit-2.jpg',
        fileName: 'DSC04955-Edit-2.jpg',
        alt: 'Wedding 2 - Photo 2',
      },
      {
        path: '/Weddings/Wedding 2/DSC05002.jpg',
        fileName: 'DSC05002.jpg',
        alt: 'Wedding 2 - Photo 3',
      },
      {
        path: '/Weddings/Wedding 2/DSC05016.jpg',
        fileName: 'DSC05016.jpg',
        alt: 'Wedding 2 - Photo 4',
      },
      {
        path: '/Weddings/Wedding 2/DSC05030.jpg',
        fileName: 'DSC05030.jpg',
        alt: 'Wedding 2 - Photo 5',
      },
      {
        path: '/Weddings/Wedding 2/DSC05107-Edit-3.jpg',
        fileName: 'DSC05107-Edit-3.jpg',
        alt: 'Wedding 2 - Photo 6',
      },
      {
        path: '/Weddings/Wedding 2/DSC05118-Edit.jpg',
        fileName: 'DSC05118-Edit.jpg',
        alt: 'Wedding 2 - Photo 7',
      },
      {
        path: '/Weddings/Wedding 2/DSC05137.jpg',
        fileName: 'DSC05137.jpg',
        alt: 'Wedding 2 - Photo 8',
      },
      {
        path: '/Weddings/Wedding 2/DSC05145-2.jpg',
        fileName: 'DSC05145-2.jpg',
        alt: 'Wedding 2 - Photo 9',
      },
      {
        path: '/Weddings/Wedding 2/DSC05197.jpg',
        fileName: 'DSC05197.jpg',
        alt: 'Wedding 2 - Photo 10',
      },
      {
        path: '/Weddings/Wedding 2/DSC05207.jpg',
        fileName: 'DSC05207.jpg',
        alt: 'Wedding 2 - Photo 11',
      },
      {
        path: '/Weddings/Wedding 2/DSC05213.jpg',
        fileName: 'DSC05213.jpg',
        alt: 'Wedding 2 - Photo 12',
      },
      {
        path: '/Weddings/Wedding 2/DSC05214.jpg',
        fileName: 'DSC05214.jpg',
        alt: 'Wedding 2 - Photo 13',
      },
      {
        path: '/Weddings/Wedding 2/DSC05239.jpg',
        fileName: 'DSC05239.jpg',
        alt: 'Wedding 2 - Photo 14',
      },
      {
        path: '/Weddings/Wedding 2/DSC05272-2.jpg',
        fileName: 'DSC05272-2.jpg',
        alt: 'Wedding 2 - Photo 15',
      },
      {
        path: '/Weddings/Wedding 2/DSC05304.jpg',
        fileName: 'DSC05304.jpg',
        alt: 'Wedding 2 - Photo 16',
      },
      {
        path: '/Weddings/Wedding 2/DSC05309.jpg',
        fileName: 'DSC05309.jpg',
        alt: 'Wedding 2 - Photo 17',
      },
      {
        path: '/Weddings/Wedding 2/DSC05428.jpg',
        fileName: 'DSC05428.jpg',
        alt: 'Wedding 2 - Photo 18',
      },
      {
        path: '/Weddings/Wedding 2/DSC05497.jpg',
        fileName: 'DSC05497.jpg',
        alt: 'Wedding 2 - Photo 19',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-03',
  },

  {
    id: 'wedding-3',
    slug: 'wedding-3',
    title: 'Wedding 3',
    description: 'A romantic wedding captured throughout the day',
    category: 'Weddings',
    coverImagePath: '/Weddings/Wedding 3/Untitled Export/Album cover 3.jpg',
    imageCount: 14,
    images: [
      {
        path: '/Weddings/Wedding 3/Untitled Export/Album cover 3.jpg',
        fileName: 'Album cover 3.jpg',
        alt: 'Wedding 3 - Photo 1',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03199.jpg',
        fileName: 'DSC03199.jpg',
        alt: 'Wedding 3 - Photo 2',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03258.jpg',
        fileName: 'DSC03258.jpg',
        alt: 'Wedding 3 - Photo 3',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03347.jpg',
        fileName: 'DSC03347.jpg',
        alt: 'Wedding 3 - Photo 4',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03384.jpg',
        fileName: 'DSC03384.jpg',
        alt: 'Wedding 3 - Photo 5',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03562.jpg',
        fileName: 'DSC03562.jpg',
        alt: 'Wedding 3 - Photo 6',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03882.jpg',
        fileName: 'DSC03882.jpg',
        alt: 'Wedding 3 - Photo 7',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03911.jpg',
        fileName: 'DSC03911.jpg',
        alt: 'Wedding 3 - Photo 8',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03955.jpg',
        fileName: 'DSC03955.jpg',
        alt: 'Wedding 3 - Photo 9',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC04017.jpg',
        fileName: 'DSC04017.jpg',
        alt: 'Wedding 3 - Photo 10',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC04085.jpg',
        fileName: 'DSC04085.jpg',
        alt: 'Wedding 3 - Photo 11',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/wedding-ceremony-nottingham-groom-bride-portrait-belvoir-castle-flowers-happiness.jpg',
        fileName: 'wedding-ceremony-nottingham-groom-bride-portrait-belvoir-castle-flowers-happiness.jpg',
        alt: 'Wedding 3 - Photo 12',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/wedding-ceremony-nottingham-guests-portrait-belvoir-castle-flowers.jpg',
        fileName: 'wedding-ceremony-nottingham-guests-portrait-belvoir-castle-flowers.jpg',
        alt: 'Wedding 3 - Photo 13',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/wedding-mother-of-bride-father-of-bride-ceremony-belvoir-castle.jpg',
        fileName: 'wedding-mother-of-bride-father-of-bride-ceremony-belvoir-castle.jpg',
        alt: 'Wedding 3 - Photo 14',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-03',
  },

  {
    id: 'engagement-session',
    slug: 'engagement-session',
    title: 'Engagement Session',
    description: 'Pre-wedding engagement photo session',
    category: 'Weddings',
    coverImagePath: '/Weddings/Engagement/Album cover eng.jpg',
    imageCount: 9,
    images: [
      {
        path: '/Weddings/Engagement/Album cover eng.jpg',
        fileName: 'Album cover eng.jpg',
        alt: 'Engagement Session - Photo 1',
      },
      {
        path: '/Weddings/Engagement/DSC06763.jpg',
        fileName: 'DSC06763.jpg',
        alt: 'Engagement Session - Photo 2',
      },
      {
        path: '/Weddings/Engagement/DSC06795.jpg',
        fileName: 'DSC06795.jpg',
        alt: 'Engagement Session - Photo 3',
      },
      {
        path: '/Weddings/Engagement/DSC06952.jpg',
        fileName: 'DSC06952.jpg',
        alt: 'Engagement Session - Photo 4',
      },
      {
        path: '/Weddings/Engagement/DSC07010-Edit.jpg',
        fileName: 'DSC07010-Edit.jpg',
        alt: 'Engagement Session - Photo 5',
      },
      {
        path: '/Weddings/Engagement/DSC07019.jpg',
        fileName: 'DSC07019.jpg',
        alt: 'Engagement Session - Photo 6',
      },
      {
        path: '/Weddings/Engagement/DSC07100.jpg',
        fileName: 'DSC07100.jpg',
        alt: 'Engagement Session - Photo 7',
      },
      {
        path: '/Weddings/Engagement/DSC07117.jpg',
        fileName: 'DSC07117.jpg',
        alt: 'Engagement Session - Photo 8',
      },
      {
        path: '/Weddings/Engagement/DSC07254-2.jpg',
        fileName: 'DSC07254-2.jpg',
        alt: 'Engagement Session - Photo 9',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-03',
  },

  {
    id: 'architecture-interiors',
    slug: 'architecture-interiors',
    title: 'Architecture & Interiors',
    description: 'Professional architectural and interior design photography',
    category: 'Architecture',
    coverImagePath: '/Architecture and Interiors small/album Architecture and interiors cover.jpg',
    imageCount: 31,
    images: [
      {
        path: '/Architecture and Interiors small/DSC00293.jpg',
        fileName: 'DSC00293.jpg',
        alt: 'Architecture & Interiors - Photo 1',
      },
      {
        path: '/Architecture and Interiors small/DSC01126.jpg',
        fileName: 'DSC01126.jpg',
        alt: 'Architecture & Interiors - Photo 2',
      },
      {
        path: '/Architecture and Interiors small/DSC01883.jpg',
        fileName: 'DSC01883.jpg',
        alt: 'Architecture & Interiors - Photo 3',
      },
      {
        path: '/Architecture and Interiors small/DSC02274.jpg',
        fileName: 'DSC02274.jpg',
        alt: 'Architecture & Interiors - Photo 4',
      },
      {
        path: '/Architecture and Interiors small/DSC02312.jpg',
        fileName: 'DSC02312.jpg',
        alt: 'Architecture & Interiors - Photo 5',
      },
      {
        path: '/Architecture and Interiors small/DSC02461.jpg',
        fileName: 'DSC02461.jpg',
        alt: 'Architecture & Interiors - Photo 6',
      },
      {
        path: '/Architecture and Interiors small/DSC02748-Edit.jpg',
        fileName: 'DSC02748-Edit.jpg',
        alt: 'Architecture & Interiors - Photo 7',
      },
      {
        path: '/Architecture and Interiors small/DSC03379.jpg',
        fileName: 'DSC03379.jpg',
        alt: 'Architecture & Interiors - Photo 8',
      },
      {
        path: '/Architecture and Interiors small/DSC03659.jpg',
        fileName: 'DSC03659.jpg',
        alt: 'Architecture & Interiors - Photo 9',
      },
      {
        path: '/Architecture and Interiors small/DSC04340.jpg',
        fileName: 'DSC04340.jpg',
        alt: 'Architecture & Interiors - Photo 10',
      },
      {
        path: '/Architecture and Interiors small/DSC05070-2.jpg',
        fileName: 'DSC05070-2.jpg',
        alt: 'Architecture & Interiors - Photo 11',
      },
      {
        path: '/Architecture and Interiors small/DSC08906-HDR.jpg',
        fileName: 'DSC08906-HDR.jpg',
        alt: 'Architecture & Interiors - Photo 12',
      },
      {
        path: '/Architecture and Interiors small/DSC08926-HDR.jpg',
        fileName: 'DSC08926-HDR.jpg',
        alt: 'Architecture & Interiors - Photo 13',
      },
      {
        path: '/Architecture and Interiors small/DSC08976-HDR.jpg',
        fileName: 'DSC08976-HDR.jpg',
        alt: 'Architecture & Interiors - Photo 14',
      },
      {
        path: '/Architecture and Interiors small/DSC09003-HDR.jpg',
        fileName: 'DSC09003-HDR.jpg',
        alt: 'Architecture & Interiors - Photo 15',
      },
      {
        path: '/Architecture and Interiors small/DSC09018-HDR.jpg',
        fileName: 'DSC09018-HDR.jpg',
        alt: 'Architecture & Interiors - Photo 16',
      },
      {
        path: '/Architecture and Interiors small/DSC09047-HDR.jpg',
        fileName: 'DSC09047-HDR.jpg',
        alt: 'Architecture & Interiors - Photo 17',
      },
      {
        path: '/Architecture and Interiors small/DSC09084-HDR.jpg',
        fileName: 'DSC09084-HDR.jpg',
        alt: 'Architecture & Interiors - Photo 18',
      },
      {
        path: '/Architecture and Interiors small/DSC09104-HDR.jpg',
        fileName: 'DSC09104-HDR.jpg',
        alt: 'Architecture & Interiors - Photo 19',
      },
      {
        path: '/Architecture and Interiors small/DSC09261-HDR.jpg',
        fileName: 'DSC09261-HDR.jpg',
        alt: 'Architecture & Interiors - Photo 20',
      },
      {
        path: '/Architecture and Interiors small/DSC09478-HDR-Edit.jpg',
        fileName: 'DSC09478-HDR-Edit.jpg',
        alt: 'Architecture & Interiors - Photo 21',
      },
      {
        path: '/Architecture and Interiors small/DSC09507-HDR-Edit.jpg',
        fileName: 'DSC09507-HDR-Edit.jpg',
        alt: 'Architecture & Interiors - Photo 22',
      },
      {
        path: '/Architecture and Interiors small/DSC09517-HDR-Edit.jpg',
        fileName: 'DSC09517-HDR-Edit.jpg',
        alt: 'Architecture & Interiors - Photo 23',
      },
      {
        path: '/Architecture and Interiors small/DSC09527-HDR-Edit.jpg',
        fileName: 'DSC09527-HDR-Edit.jpg',
        alt: 'Architecture & Interiors - Photo 24',
      },
      {
        path: '/Architecture and Interiors small/DSC09645-HDR.jpg',
        fileName: 'DSC09645-HDR.jpg',
        alt: 'Architecture & Interiors - Photo 25',
      },
      {
        path: '/Architecture and Interiors small/DSC09665.jpg',
        fileName: 'DSC09665.jpg',
        alt: 'Architecture & Interiors - Photo 26',
      },
      {
        path: '/Architecture and Interiors small/DSC09695-HDR-Edit-Edit.jpg',
        fileName: 'DSC09695-HDR-Edit-Edit.jpg',
        alt: 'Architecture & Interiors - Photo 27',
      },
      {
        path: '/Architecture and Interiors small/DSC09728-HDR-Editqq.jpg',
        fileName: 'DSC09728-HDR-Editqq.jpg',
        alt: 'Architecture & Interiors - Photo 28',
      },
      {
        path: '/Architecture and Interiors small/DSC09772.jpg',
        fileName: 'DSC09772.jpg',
        alt: 'Architecture & Interiors - Photo 29',
      },
      {
        path: '/Architecture and Interiors small/DSC09854.jpg',
        fileName: 'DSC09854.jpg',
        alt: 'Architecture & Interiors - Photo 30',
      },
      {
        path: '/Architecture and Interiors small/album Architecture and interiors cover.jpg',
        fileName: 'album Architecture and interiors cover.jpg',
        alt: 'Architecture & Interiors - Photo 31',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-03',
  },

  {
    id: 'branding',
    slug: 'branding',
    title: 'Branding',
    description: 'Corporate branding and product photography',
    category: 'Branding',
    coverImagePath: '/Branding small/album Branding cover.jpg',
    imageCount: 30,
    images: [
      {
        path: '/Branding small/DSC00179.jpg',
        fileName: 'DSC00179.jpg',
        alt: 'Branding - Photo 1',
      },
      {
        path: '/Branding small/DSC00193.jpg',
        fileName: 'DSC00193.jpg',
        alt: 'Branding - Photo 2',
      },
      {
        path: '/Branding small/DSC00254.jpg',
        fileName: 'DSC00254.jpg',
        alt: 'Branding - Photo 3',
      },
      {
        path: '/Branding small/DSC04901-Edit.jpg',
        fileName: 'DSC04901-Edit.jpg',
        alt: 'Branding - Photo 4',
      },
      {
        path: '/Branding small/DSC04920.jpg',
        fileName: 'DSC04920.jpg',
        alt: 'Branding - Photo 5',
      },
      {
        path: '/Branding small/DSC04932.jpg',
        fileName: 'DSC04932.jpg',
        alt: 'Branding - Photo 6',
      },
      {
        path: '/Branding small/DSC04948.jpg',
        fileName: 'DSC04948.jpg',
        alt: 'Branding - Photo 7',
      },
      {
        path: '/Branding small/DSC04987.jpg',
        fileName: 'DSC04987.jpg',
        alt: 'Branding - Photo 8',
      },
      {
        path: '/Branding small/DSC05042.jpg',
        fileName: 'DSC05042.jpg',
        alt: 'Branding - Photo 9',
      },
      {
        path: '/Branding small/DSC05097.jpg',
        fileName: 'DSC05097.jpg',
        alt: 'Branding - Photo 10',
      },
      {
        path: '/Branding small/DSC05124.jpg',
        fileName: 'DSC05124.jpg',
        alt: 'Branding - Photo 11',
      },
      {
        path: '/Branding small/DSC05253.jpg',
        fileName: 'DSC05253.jpg',
        alt: 'Branding - Photo 12',
      },
      {
        path: '/Branding small/DSC05268.jpg',
        fileName: 'DSC05268.jpg',
        alt: 'Branding - Photo 13',
      },
      {
        path: '/Branding small/DSC05319.jpg',
        fileName: 'DSC05319.jpg',
        alt: 'Branding - Photo 14',
      },
      {
        path: '/Branding small/DSC05476.jpg',
        fileName: 'DSC05476.jpg',
        alt: 'Branding - Photo 15',
      },
      {
        path: '/Branding small/DSC07238.jpg',
        fileName: 'DSC07238.jpg',
        alt: 'Branding - Photo 16',
      },
      {
        path: '/Branding small/DSC07247.jpg',
        fileName: 'DSC07247.jpg',
        alt: 'Branding - Photo 17',
      },
      {
        path: '/Branding small/DSC07250.jpg',
        fileName: 'DSC07250.jpg',
        alt: 'Branding - Photo 18',
      },
      {
        path: '/Branding small/DSC07264-Edit.jpg',
        fileName: 'DSC07264-Edit.jpg',
        alt: 'Branding - Photo 19',
      },
      {
        path: '/Branding small/DSC07281.jpg',
        fileName: 'DSC07281.jpg',
        alt: 'Branding - Photo 20',
      },
      {
        path: '/Branding small/DSC07328.jpg',
        fileName: 'DSC07328.jpg',
        alt: 'Branding - Photo 21',
      },
      {
        path: '/Branding small/DSC07353.jpg',
        fileName: 'DSC07353.jpg',
        alt: 'Branding - Photo 22',
      },
      {
        path: '/Branding small/DSC07358.jpg',
        fileName: 'DSC07358.jpg',
        alt: 'Branding - Photo 23',
      },
      {
        path: '/Branding small/DSC07385.jpg',
        fileName: 'DSC07385.jpg',
        alt: 'Branding - Photo 24',
      },
      {
        path: '/Branding small/DSC07385s.jpg',
        fileName: 'DSC07385s.jpg',
        alt: 'Branding - Photo 25',
      },
      {
        path: '/Branding small/DSC07497.jpg',
        fileName: 'DSC07497.jpg',
        alt: 'Branding - Photo 26',
      },
      {
        path: '/Branding small/DSC07517.jpg',
        fileName: 'DSC07517.jpg',
        alt: 'Branding - Photo 27',
      },
      {
        path: '/Branding small/DSC07664.jpg',
        fileName: 'DSC07664.jpg',
        alt: 'Branding - Photo 28',
      },
      {
        path: '/Branding small/album Branding cover.jpg',
        fileName: 'album Branding cover.jpg',
        alt: 'Branding - Photo 29',
      },
      {
        path: '/Branding small/qDSC00300.jpg',
        fileName: 'qDSC00300.jpg',
        alt: 'Branding - Photo 30',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-03',
  },

  {
    id: 'children-family',
    slug: 'children-family',
    title: 'Children & Family',
    description: 'Heartwarming family and children photography',
    category: 'Family',
    coverImagePath: '/Children and family/Album cover kids.jpg',
    imageCount: 99,
    images: [
      {
        path: '/Children and family/Album cover kids.jpg',
        fileName: 'Album cover kids.jpg',
        alt: 'Children & Family - Photo 1',
      },
      {
        path: '/Children and family/DSC00120.jpg',
        fileName: 'DSC00120.jpg',
        alt: 'Children & Family - Photo 2',
      },
      {
        path: '/Children and family/DSC00583.jpg',
        fileName: 'DSC00583.jpg',
        alt: 'Children & Family - Photo 3',
      },
      {
        path: '/Children and family/DSC00715-Edit.jpg',
        fileName: 'DSC00715-Edit.jpg',
        alt: 'Children & Family - Photo 4',
      },
      {
        path: '/Children and family/DSC01297.jpg',
        fileName: 'DSC01297.jpg',
        alt: 'Children & Family - Photo 5',
      },
      {
        path: '/Children and family/DSC01320.jpg',
        fileName: 'DSC01320.jpg',
        alt: 'Children & Family - Photo 6',
      },
      {
        path: '/Children and family/DSC01529.jpg',
        fileName: 'DSC01529.jpg',
        alt: 'Children & Family - Photo 7',
      },
      {
        path: '/Children and family/DSC01690.jpg',
        fileName: 'DSC01690.jpg',
        alt: 'Children & Family - Photo 8',
      },
      {
        path: '/Children and family/DSC01979.jpg',
        fileName: 'DSC01979.jpg',
        alt: 'Children & Family - Photo 9',
      },
      {
        path: '/Children and family/DSC02103.jpg',
        fileName: 'DSC02103.jpg',
        alt: 'Children & Family - Photo 10',
      },
      {
        path: '/Children and family/DSC02247.jpg',
        fileName: 'DSC02247.jpg',
        alt: 'Children & Family - Photo 11',
      },
      {
        path: '/Children and family/DSC02490.jpg',
        fileName: 'DSC02490.jpg',
        alt: 'Children & Family - Photo 12',
      },
      {
        path: '/Children and family/DSC02611.jpg',
        fileName: 'DSC02611.jpg',
        alt: 'Children & Family - Photo 13',
      },
      {
        path: '/Children and family/DSC02659-Edit-2.jpg',
        fileName: 'DSC02659-Edit-2.jpg',
        alt: 'Children & Family - Photo 14',
      },
      {
        path: '/Children and family/DSC02676.jpg',
        fileName: 'DSC02676.jpg',
        alt: 'Children & Family - Photo 15',
      },
      {
        path: '/Children and family/DSC02758.jpg',
        fileName: 'DSC02758.jpg',
        alt: 'Children & Family - Photo 16',
      },
      {
        path: '/Children and family/DSC02899.jpg',
        fileName: 'DSC02899.jpg',
        alt: 'Children & Family - Photo 17',
      },
      {
        path: '/Children and family/DSC02941.jpg',
        fileName: 'DSC02941.jpg',
        alt: 'Children & Family - Photo 18',
      },
      {
        path: '/Children and family/DSC03065-Edit.jpg',
        fileName: 'DSC03065-Edit.jpg',
        alt: 'Children & Family - Photo 19',
      },
      {
        path: '/Children and family/DSC03259-Edit.jpg',
        fileName: 'DSC03259-Edit.jpg',
        alt: 'Children & Family - Photo 20',
      },
      {
        path: '/Children and family/DSC03271.jpg',
        fileName: 'DSC03271.jpg',
        alt: 'Children & Family - Photo 21',
      },
      {
        path: '/Children and family/DSC03299.jpg',
        fileName: 'DSC03299.jpg',
        alt: 'Children & Family - Photo 22',
      },
      {
        path: '/Children and family/DSC03319-Edit.jpg',
        fileName: 'DSC03319-Edit.jpg',
        alt: 'Children & Family - Photo 23',
      },
      {
        path: '/Children and family/DSC03355-Edit.jpg',
        fileName: 'DSC03355-Edit.jpg',
        alt: 'Children & Family - Photo 24',
      },
      {
        path: '/Children and family/DSC03432.jpg',
        fileName: 'DSC03432.jpg',
        alt: 'Children & Family - Photo 25',
      },
      {
        path: '/Children and family/DSC03437.jpg',
        fileName: 'DSC03437.jpg',
        alt: 'Children & Family - Photo 26',
      },
      {
        path: '/Children and family/DSC03449.jpg',
        fileName: 'DSC03449.jpg',
        alt: 'Children & Family - Photo 27',
      },
      {
        path: '/Children and family/DSC03450.jpg',
        fileName: 'DSC03450.jpg',
        alt: 'Children & Family - Photo 28',
      },
      {
        path: '/Children and family/DSC03456-Edit.jpg',
        fileName: 'DSC03456-Edit.jpg',
        alt: 'Children & Family - Photo 29',
      },
      {
        path: '/Children and family/DSC03586-2.jpg',
        fileName: 'DSC03586-2.jpg',
        alt: 'Children & Family - Photo 30',
      },
      {
        path: '/Children and family/DSC03657.jpg',
        fileName: 'DSC03657.jpg',
        alt: 'Children & Family - Photo 31',
      },
      {
        path: '/Children and family/DSC03708.jpg',
        fileName: 'DSC03708.jpg',
        alt: 'Children & Family - Photo 32',
      },
      {
        path: '/Children and family/DSC03716.jpg',
        fileName: 'DSC03716.jpg',
        alt: 'Children & Family - Photo 33',
      },
      {
        path: '/Children and family/DSC03823.jpg',
        fileName: 'DSC03823.jpg',
        alt: 'Children & Family - Photo 34',
      },
      {
        path: '/Children and family/DSC03858.jpg',
        fileName: 'DSC03858.jpg',
        alt: 'Children & Family - Photo 35',
      },
      {
        path: '/Children and family/DSC03898.jpg',
        fileName: 'DSC03898.jpg',
        alt: 'Children & Family - Photo 36',
      },
      {
        path: '/Children and family/DSC039611.jpg',
        fileName: 'DSC039611.jpg',
        alt: 'Children & Family - Photo 37',
      },
      {
        path: '/Children and family/DSC03993-2.jpg',
        fileName: 'DSC03993-2.jpg',
        alt: 'Children & Family - Photo 38',
      },
      {
        path: '/Children and family/DSC04390dd.jpg',
        fileName: 'DSC04390dd.jpg',
        alt: 'Children & Family - Photo 39',
      },
      {
        path: '/Children and family/DSC04446-2.jpg',
        fileName: 'DSC04446-2.jpg',
        alt: 'Children & Family - Photo 40',
      },
      {
        path: '/Children and family/DSC04829-Edit.jpg',
        fileName: 'DSC04829-Edit.jpg',
        alt: 'Children & Family - Photo 41',
      },
      {
        path: '/Children and family/DSC05146-Edit-Edit-2.jpg',
        fileName: 'DSC05146-Edit-Edit-2.jpg',
        alt: 'Children & Family - Photo 42',
      },
      {
        path: '/Children and family/DSC05346.jpg',
        fileName: 'DSC05346.jpg',
        alt: 'Children & Family - Photo 43',
      },
      {
        path: '/Children and family/DSC05378.jpg',
        fileName: 'DSC05378.jpg',
        alt: 'Children & Family - Photo 44',
      },
      {
        path: '/Children and family/DSC05403.jpg',
        fileName: 'DSC05403.jpg',
        alt: 'Children & Family - Photo 45',
      },
      {
        path: '/Children and family/DSC05422.jpg',
        fileName: 'DSC05422.jpg',
        alt: 'Children & Family - Photo 46',
      },
      {
        path: '/Children and family/DSC05451.jpg',
        fileName: 'DSC05451.jpg',
        alt: 'Children & Family - Photo 47',
      },
      {
        path: '/Children and family/DSC05639.jpg',
        fileName: 'DSC05639.jpg',
        alt: 'Children & Family - Photo 48',
      },
      {
        path: '/Children and family/DSC05670.jpg',
        fileName: 'DSC05670.jpg',
        alt: 'Children & Family - Photo 49',
      },
      {
        path: '/Children and family/DSC05711.jpg',
        fileName: 'DSC05711.jpg',
        alt: 'Children & Family - Photo 50',
      },
      {
        path: '/Children and family/DSC05809-Edit.jpg',
        fileName: 'DSC05809-Edit.jpg',
        alt: 'Children & Family - Photo 51',
      },
      {
        path: '/Children and family/DSC05966.jpg',
        fileName: 'DSC05966.jpg',
        alt: 'Children & Family - Photo 52',
      },
      {
        path: '/Children and family/DSC05992.jpg',
        fileName: 'DSC05992.jpg',
        alt: 'Children & Family - Photo 53',
      },
      {
        path: '/Children and family/DSC06030.jpg',
        fileName: 'DSC06030.jpg',
        alt: 'Children & Family - Photo 54',
      },
      {
        path: '/Children and family/DSC06082.jpg',
        fileName: 'DSC06082.jpg',
        alt: 'Children & Family - Photo 55',
      },
      {
        path: '/Children and family/DSC06140.jpg',
        fileName: 'DSC06140.jpg',
        alt: 'Children & Family - Photo 56',
      },
      {
        path: '/Children and family/DSC06233.jpg',
        fileName: 'DSC06233.jpg',
        alt: 'Children & Family - Photo 57',
      },
      {
        path: '/Children and family/DSC06375.jpg',
        fileName: 'DSC06375.jpg',
        alt: 'Children & Family - Photo 58',
      },
      {
        path: '/Children and family/DSC06417.jpg',
        fileName: 'DSC06417.jpg',
        alt: 'Children & Family - Photo 59',
      },
      {
        path: '/Children and family/DSC06435.jpg',
        fileName: 'DSC06435.jpg',
        alt: 'Children & Family - Photo 60',
      },
      {
        path: '/Children and family/DSC06661.jpg',
        fileName: 'DSC06661.jpg',
        alt: 'Children & Family - Photo 61',
      },
      {
        path: '/Children and family/DSC07134.jpg',
        fileName: 'DSC07134.jpg',
        alt: 'Children & Family - Photo 62',
      },
      {
        path: '/Children and family/DSC07713-Enhanced-NR-5.jpg',
        fileName: 'DSC07713-Enhanced-NR-5.jpg',
        alt: 'Children & Family - Photo 63',
      },
      {
        path: '/Children and family/DSC08159.jpg',
        fileName: 'DSC08159.jpg',
        alt: 'Children & Family - Photo 64',
      },
      {
        path: '/Children and family/DSC08450-Editwe.jpg',
        fileName: 'DSC08450-Editwe.jpg',
        alt: 'Children & Family - Photo 65',
      },
      {
        path: '/Children and family/DSC0863522.jpg',
        fileName: 'DSC0863522.jpg',
        alt: 'Children & Family - Photo 66',
      },
      {
        path: '/Children and family/DSC08649.jpg',
        fileName: 'DSC08649.jpg',
        alt: 'Children & Family - Photo 67',
      },
      {
        path: '/Children and family/DSC08715.jpg',
        fileName: 'DSC08715.jpg',
        alt: 'Children & Family - Photo 68',
      },
      {
        path: '/Children and family/DSC08725.jpg',
        fileName: 'DSC08725.jpg',
        alt: 'Children & Family - Photo 69',
      },
      {
        path: '/Children and family/DSC09299.jpg',
        fileName: 'DSC09299.jpg',
        alt: 'Children & Family - Photo 70',
      },
      {
        path: '/Children and family/DSC09517-Edit1.jpg',
        fileName: 'DSC09517-Edit1.jpg',
        alt: 'Children & Family - Photo 71',
      },
      {
        path: '/Children and family/DSC09613.jpg',
        fileName: 'DSC09613.jpg',
        alt: 'Children & Family - Photo 72',
      },
      {
        path: '/Children and family/DSC09776.jpg',
        fileName: 'DSC09776.jpg',
        alt: 'Children & Family - Photo 73',
      },
      {
        path: '/Children and family/DSC09811.jpg',
        fileName: 'DSC09811.jpg',
        alt: 'Children & Family - Photo 74',
      },
      {
        path: '/Children and family/Kid-portrait-nottingham-book.jpg',
        fileName: 'Kid-portrait-nottingham-book.jpg',
        alt: 'Children & Family - Photo 75',
      },
      {
        path: '/Children and family/Kid-portrait-nottingham-journey-life-photography.jpg',
        fileName: 'Kid-portrait-nottingham-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 76',
      },
      {
        path: '/Children and family/baby-and-daddy-portrait-beautiful-blue-eyes-nottingham-photographer.jpg',
        fileName: 'baby-and-daddy-portrait-beautiful-blue-eyes-nottingham-photographer.jpg',
        alt: 'Children & Family - Photo 77',
      },
      {
        path: '/Children and family/boy-child-portrait-nottingham-journey-life-photography.jpg',
        fileName: 'boy-child-portrait-nottingham-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 78',
      },
      {
        path: '/Children and family/boy-with-daisies-spring-family-photoshoots-nottingham.jpg',
        fileName: 'boy-with-daisies-spring-family-photoshoots-nottingham.jpg',
        alt: 'Children & Family - Photo 79',
      },
      {
        path: '/Children and family/child-christening-birthday-party-portrait-family-photoshoot-journey-life-photography-girl-on-a-swing-nottingham.jpg',
        fileName: 'child-christening-birthday-party-portrait-family-photoshoot-journey-life-photography-girl-on-a-swing-nottingham.jpg',
        alt: 'Children & Family - Photo 80',
      },
      {
        path: '/Children and family/child-christening-portrait-family-photoshoot-journey-life-photography.jpg',
        fileName: 'child-christening-portrait-family-photoshoot-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 81',
      },
      {
        path: '/Children and family/child-first-birthday-party-portrait-family-photoshoot-cake-journey-life-photography.jpg',
        fileName: 'child-first-birthday-party-portrait-family-photoshoot-cake-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 82',
      },
      {
        path: '/Children and family/child-first-birthday-party-portrait-family-photoshoot-cake-smash-journey-life-photography-event-nottingham.jpg',
        fileName: 'child-first-birthday-party-portrait-family-photoshoot-cake-smash-journey-life-photography-event-nottingham.jpg',
        alt: 'Children & Family - Photo 83',
      },
      {
        path: '/Children and family/child-first-birthday-party-portrait-family-photoshoot-journey-life-photography.jpg',
        fileName: 'child-first-birthday-party-portrait-family-photoshoot-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 84',
      },
      {
        path: '/Children and family/child-jump-gymnastics-portrait-nottingham-journey-life-photography.jpg',
        fileName: 'child-jump-gymnastics-portrait-nottingham-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 85',
      },
      {
        path: '/Children and family/child-portrait-nottingham-journey-life-photography.jpg',
        fileName: 'child-portrait-nottingham-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 86',
      },
      {
        path: '/Children and family/child-read-book-portrait-nottingham-journey-life-photography.jpg',
        fileName: 'child-read-book-portrait-nottingham-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 87',
      },
      {
        path: '/Children and family/child-smiley-portrait-nottingham-birthday-party.jpg',
        fileName: 'child-smiley-portrait-nottingham-birthday-party.jpg',
        alt: 'Children & Family - Photo 88',
      },
      {
        path: '/Children and family/child-smiley-portrait-nottingham.jpg',
        fileName: 'child-smiley-portrait-nottingham.jpg',
        alt: 'Children & Family - Photo 89',
      },
      {
        path: '/Children and family/crossfit-kids-portraits-sports-happy-kids-photography-journey-life-photography-smiles.jpg',
        fileName: 'crossfit-kids-portraits-sports-happy-kids-photography-journey-life-photography-smiles.jpg',
        alt: 'Children & Family - Photo 90',
      },
      {
        path: '/Children and family/crossfit-kids-portraits-sports-photography-journey-life-photography-smiles.jpg',
        fileName: 'crossfit-kids-portraits-sports-photography-journey-life-photography-smiles.jpg',
        alt: 'Children & Family - Photo 91',
      },
      {
        path: '/Children and family/girl-funky-portrait-nottingham-journey-life-photography.jpg',
        fileName: 'girl-funky-portrait-nottingham-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 92',
      },
      {
        path: '/Children and family/girl-portrait-autumn-nottingham-beautiful-journey-life-photography.jpg',
        fileName: 'girl-portrait-autumn-nottingham-beautiful-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 93',
      },
      {
        path: '/Children and family/girl-portrait-dovedale-nottingham-beautiful-journey-life-photography.jpg',
        fileName: 'girl-portrait-dovedale-nottingham-beautiful-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 94',
      },
      {
        path: '/Children and family/girl-portrait-playground-party-nottingham-beautiful-journey-life-photography.jpg',
        fileName: 'girl-portrait-playground-party-nottingham-beautiful-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 95',
      },
      {
        path: '/Children and family/interesting-portrait-of-a-child-smiley-portrait-nottingham.jpg',
        fileName: 'interesting-portrait-of-a-child-smiley-portrait-nottingham.jpg',
        alt: 'Children & Family - Photo 96',
      },
      {
        path: '/Children and family/kid-portrait-bluebell-forest-nottingham-journey-life-photography-woods-flowers.jpg',
        fileName: 'kid-portrait-bluebell-forest-nottingham-journey-life-photography-woods-flowers.jpg',
        alt: 'Children & Family - Photo 97',
      },
      {
        path: '/Children and family/kids-different-portrait-shadows-and-light-journey-life-photography-nottingham.jpg',
        fileName: 'kids-different-portrait-shadows-and-light-journey-life-photography-nottingham.jpg',
        alt: 'Children & Family - Photo 98',
      },
      {
        path: '/Children and family/wild-garlic-portrait-girl-nottingham-woods-nature-forest-journey-life-photography.jpg',
        fileName: 'wild-garlic-portrait-girl-nottingham-woods-nature-forest-journey-life-photography.jpg',
        alt: 'Children & Family - Photo 99',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-03',
  },

  {
    id: 'corporate-events',
    slug: 'corporate-events',
    title: 'Corporate Events',
    description: 'Professional corporate event photography',
    category: 'Corporate',
    coverImagePath: '/Corporate small/Album cover.jpg',
    imageCount: 17,
    images: [
      {
        path: '/Corporate small/Album cover.jpg',
        fileName: 'Album cover.jpg',
        alt: 'Corporate Events - Photo 1',
      },
      {
        path: '/Corporate small/BW DSC09218-Edit-2.jpg',
        fileName: 'BW DSC09218-Edit-2.jpg',
        alt: 'Corporate Events - Photo 2',
      },
      {
        path: '/Corporate small/BW DSC09238-Edit-2-2.jpg',
        fileName: 'BW DSC09238-Edit-2-2.jpg',
        alt: 'Corporate Events - Photo 3',
      },
      {
        path: '/Corporate small/BW DSC09339-Edit-2.jpg',
        fileName: 'BW DSC09339-Edit-2.jpg',
        alt: 'Corporate Events - Photo 4',
      },
      {
        path: '/Corporate small/DSC03731-Edit.jpg',
        fileName: 'DSC03731-Edit.jpg',
        alt: 'Corporate Events - Photo 5',
      },
      {
        path: '/Corporate small/DSC03799-Edit-3.jpg',
        fileName: 'DSC03799-Edit-3.jpg',
        alt: 'Corporate Events - Photo 6',
      },
      {
        path: '/Corporate small/DSC03816-Edit-Edit-2.jpg',
        fileName: 'DSC03816-Edit-Edit-2.jpg',
        alt: 'Corporate Events - Photo 7',
      },
      {
        path: '/Corporate small/DSC03868-Edit.jpg',
        fileName: 'DSC03868-Edit.jpg',
        alt: 'Corporate Events - Photo 8',
      },
      {
        path: '/Corporate small/DSC04059-Edit.jpg',
        fileName: 'DSC04059-Edit.jpg',
        alt: 'Corporate Events - Photo 9',
      },
      {
        path: '/Corporate small/DSC05752.jpg',
        fileName: 'DSC05752.jpg',
        alt: 'Corporate Events - Photo 10',
      },
      {
        path: '/Corporate small/DSC05787.jpg',
        fileName: 'DSC05787.jpg',
        alt: 'Corporate Events - Photo 11',
      },
      {
        path: '/Corporate small/DSC05846.jpg',
        fileName: 'DSC05846.jpg',
        alt: 'Corporate Events - Photo 12',
      },
      {
        path: '/Corporate small/DSC05924.jpg',
        fileName: 'DSC05924.jpg',
        alt: 'Corporate Events - Photo 13',
      },
      {
        path: '/Corporate small/DSC05987.jpg',
        fileName: 'DSC05987.jpg',
        alt: 'Corporate Events - Photo 14',
      },
      {
        path: '/Corporate small/DSC06078_(2).jpg',
        fileName: 'DSC06078_(2).jpg',
        alt: 'Corporate Events - Photo 15',
      },
      {
        path: '/Corporate small/DSC06224.jpg',
        fileName: 'DSC06224.jpg',
        alt: 'Corporate Events - Photo 16',
      },
      {
        path: '/Corporate small/DSC09256-Edit-2-Edit M.jpg',
        fileName: 'DSC09256-Edit-2-Edit M.jpg',
        alt: 'Corporate Events - Photo 17',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-03',
  },

  {
    id: 'travel-photography',
    slug: 'travel-photography',
    title: 'Travel Photography',
    description: 'Travel and adventure photography from around the world',
    category: 'Travel',
    coverImagePath: '/Travel small/Albu cover travel.jpg',
    imageCount: 57,
    images: [
      {
        path: '/Travel small/Albu cover travel.jpg',
        fileName: 'Albu cover travel.jpg',
        alt: 'Travel Photography - Photo 1',
      },
      {
        path: '/Travel small/DSC00018.jpg',
        fileName: 'DSC00018.jpg',
        alt: 'Travel Photography - Photo 2',
      },
      {
        path: '/Travel small/DSC00710.jpg',
        fileName: 'DSC00710.jpg',
        alt: 'Travel Photography - Photo 3',
      },
      {
        path: '/Travel small/DSC00722.jpg',
        fileName: 'DSC00722.jpg',
        alt: 'Travel Photography - Photo 4',
      },
      {
        path: '/Travel small/DSC00800.jpg',
        fileName: 'DSC00800.jpg',
        alt: 'Travel Photography - Photo 5',
      },
      {
        path: '/Travel small/DSC00818-2.jpg',
        fileName: 'DSC00818-2.jpg',
        alt: 'Travel Photography - Photo 6',
      },
      {
        path: '/Travel small/DSC00842.jpg',
        fileName: 'DSC00842.jpg',
        alt: 'Travel Photography - Photo 7',
      },
      {
        path: '/Travel small/DSC01104.jpg',
        fileName: 'DSC01104.jpg',
        alt: 'Travel Photography - Photo 8',
      },
      {
        path: '/Travel small/DSC01207.jpg',
        fileName: 'DSC01207.jpg',
        alt: 'Travel Photography - Photo 9',
      },
      {
        path: '/Travel small/DSC01618.jpg',
        fileName: 'DSC01618.jpg',
        alt: 'Travel Photography - Photo 10',
      },
      {
        path: '/Travel small/DSC01759.jpg',
        fileName: 'DSC01759.jpg',
        alt: 'Travel Photography - Photo 11',
      },
      {
        path: '/Travel small/DSC01943.jpg',
        fileName: 'DSC01943.jpg',
        alt: 'Travel Photography - Photo 12',
      },
      {
        path: '/Travel small/DSC02023.jpg',
        fileName: 'DSC02023.jpg',
        alt: 'Travel Photography - Photo 13',
      },
      {
        path: '/Travel small/DSC02464.jpg',
        fileName: 'DSC02464.jpg',
        alt: 'Travel Photography - Photo 14',
      },
      {
        path: '/Travel small/DSC02472.jpg',
        fileName: 'DSC02472.jpg',
        alt: 'Travel Photography - Photo 15',
      },
      {
        path: '/Travel small/DSC02741.jpg',
        fileName: 'DSC02741.jpg',
        alt: 'Travel Photography - Photo 16',
      },
      {
        path: '/Travel small/DSC02881-Edit-4.jpg',
        fileName: 'DSC02881-Edit-4.jpg',
        alt: 'Travel Photography - Photo 17',
      },
      {
        path: '/Travel small/DSC03015.jpg',
        fileName: 'DSC03015.jpg',
        alt: 'Travel Photography - Photo 18',
      },
      {
        path: '/Travel small/DSC03376-2.jpg',
        fileName: 'DSC03376-2.jpg',
        alt: 'Travel Photography - Photo 19',
      },
      {
        path: '/Travel small/DSC03451.jpg',
        fileName: 'DSC03451.jpg',
        alt: 'Travel Photography - Photo 20',
      },
      {
        path: '/Travel small/DSC03777.jpg',
        fileName: 'DSC03777.jpg',
        alt: 'Travel Photography - Photo 21',
      },
      {
        path: '/Travel small/DSC03995-4.jpg',
        fileName: 'DSC03995-4.jpg',
        alt: 'Travel Photography - Photo 22',
      },
      {
        path: '/Travel small/DSC03995-5.jpg',
        fileName: 'DSC03995-5.jpg',
        alt: 'Travel Photography - Photo 23',
      },
      {
        path: '/Travel small/DSC04033-3.jpg',
        fileName: 'DSC04033-3.jpg',
        alt: 'Travel Photography - Photo 24',
      },
      {
        path: '/Travel small/DSC04311.jpg',
        fileName: 'DSC04311.jpg',
        alt: 'Travel Photography - Photo 25',
      },
      {
        path: '/Travel small/DSC04379-2.jpg',
        fileName: 'DSC04379-2.jpg',
        alt: 'Travel Photography - Photo 26',
      },
      {
        path: '/Travel small/DSC04813.jpg',
        fileName: 'DSC04813.jpg',
        alt: 'Travel Photography - Photo 27',
      },
      {
        path: '/Travel small/DSC04946-Edit.jpg',
        fileName: 'DSC04946-Edit.jpg',
        alt: 'Travel Photography - Photo 28',
      },
      {
        path: '/Travel small/DSC04964.jpg',
        fileName: 'DSC04964.jpg',
        alt: 'Travel Photography - Photo 29',
      },
      {
        path: '/Travel small/DSC05040.jpg',
        fileName: 'DSC05040.jpg',
        alt: 'Travel Photography - Photo 30',
      },
      {
        path: '/Travel small/DSC05043.jpg',
        fileName: 'DSC05043.jpg',
        alt: 'Travel Photography - Photo 31',
      },
      {
        path: '/Travel small/DSC05083.jpg',
        fileName: 'DSC05083.jpg',
        alt: 'Travel Photography - Photo 32',
      },
      {
        path: '/Travel small/DSC05338-Edit.jpg',
        fileName: 'DSC05338-Edit.jpg',
        alt: 'Travel Photography - Photo 33',
      },
      {
        path: '/Travel small/DSC05807.jpg',
        fileName: 'DSC05807.jpg',
        alt: 'Travel Photography - Photo 34',
      },
      {
        path: '/Travel small/DSC06115-Edit.jpg',
        fileName: 'DSC06115-Edit.jpg',
        alt: 'Travel Photography - Photo 35',
      },
      {
        path: '/Travel small/DSC06290.jpg',
        fileName: 'DSC06290.jpg',
        alt: 'Travel Photography - Photo 36',
      },
      {
        path: '/Travel small/DSC06394-Edit.jpg',
        fileName: 'DSC06394-Edit.jpg',
        alt: 'Travel Photography - Photo 37',
      },
      {
        path: '/Travel small/DSC06399-Edit.jpg',
        fileName: 'DSC06399-Edit.jpg',
        alt: 'Travel Photography - Photo 38',
      },
      {
        path: '/Travel small/DSC06427.jpg',
        fileName: 'DSC06427.jpg',
        alt: 'Travel Photography - Photo 39',
      },
      {
        path: '/Travel small/DSC06456.jpg',
        fileName: 'DSC06456.jpg',
        alt: 'Travel Photography - Photo 40',
      },
      {
        path: '/Travel small/DSC06537.jpg',
        fileName: 'DSC06537.jpg',
        alt: 'Travel Photography - Photo 41',
      },
      {
        path: '/Travel small/DSC06867-EditgbdDF.jpg',
        fileName: 'DSC06867-EditgbdDF.jpg',
        alt: 'Travel Photography - Photo 42',
      },
      {
        path: '/Travel small/DSC06920-Edit.jpg',
        fileName: 'DSC06920-Edit.jpg',
        alt: 'Travel Photography - Photo 43',
      },
      {
        path: '/Travel small/DSC07086.jpg',
        fileName: 'DSC07086.jpg',
        alt: 'Travel Photography - Photo 44',
      },
      {
        path: '/Travel small/DSC08936.jpg',
        fileName: 'DSC08936.jpg',
        alt: 'Travel Photography - Photo 45',
      },
      {
        path: '/Travel small/DSC09023.jpg',
        fileName: 'DSC09023.jpg',
        alt: 'Travel Photography - Photo 46',
      },
      {
        path: '/Travel small/DSC09103.jpg',
        fileName: 'DSC09103.jpg',
        alt: 'Travel Photography - Photo 47',
      },
      {
        path: '/Travel small/DSC09140.jpg',
        fileName: 'DSC09140.jpg',
        alt: 'Travel Photography - Photo 48',
      },
      {
        path: '/Travel small/DSC09298.jpg',
        fileName: 'DSC09298.jpg',
        alt: 'Travel Photography - Photo 49',
      },
      {
        path: '/Travel small/DSC09786.jpg',
        fileName: 'DSC09786.jpg',
        alt: 'Travel Photography - Photo 50',
      },
      {
        path: '/Travel small/DSC09831.jpg',
        fileName: 'DSC09831.jpg',
        alt: 'Travel Photography - Photo 51',
      },
      {
        path: '/Travel small/DSC09849.jpg',
        fileName: 'DSC09849.jpg',
        alt: 'Travel Photography - Photo 52',
      },
      {
        path: '/Travel small/italy-church-landscape--journey-life-photography.jpg',
        fileName: 'italy-church-landscape--journey-life-photography.jpg',
        alt: 'Travel Photography - Photo 53',
      },
      {
        path: '/Travel small/ladscape-nottingham-photographer-child.jpg',
        fileName: 'ladscape-nottingham-photographer-child.jpg',
        alt: 'Travel Photography - Photo 54',
      },
      {
        path: '/Travel small/landscape-seaside-nottingham-photographer-travel-photography.jpg',
        fileName: 'landscape-seaside-nottingham-photographer-travel-photography.jpg',
        alt: 'Travel Photography - Photo 55',
      },
      {
        path: '/Travel small/laundry-italy-landscape.jpg',
        fileName: 'laundry-italy-landscape.jpg',
        alt: 'Travel Photography - Photo 56',
      },
      {
        path: '/Travel small/old-man-portrait-italy.jpg',
        fileName: 'old-man-portrait-italy.jpg',
        alt: 'Travel Photography - Photo 57',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-03',
  }
];

// Helper to get all albums with proper image URLs
export function getAllAlbums() {
  return albumsData.map(album => ({
    ...album,
    coverImage: album.coverImagePath ? getThumbnailUrl(album.coverImagePath) : '/placeholder-album.jpg',
    coverImageFull: album.coverImagePath ? getImageUrl(album.coverImagePath) : '/placeholder-album.jpg',
  }));
}

// Helper to get album by slug
export function getAlbumBySlug(slug: string) {
  return albumsData.find(album => album.slug === slug);
}

// Helper to get album images with full URLs
export function getAlbumImages(albumId: string) {
  const album = albumsData.find(a => a.id === albumId);
  if (!album) return [];

  return album.images.map(img => ({
    ...img,
    url: getImageUrl(img.path),
    thumbnailUrl: getThumbnailUrl(img.path),
  }));
}
