// =====================
// Album Configuration with Full Photo Lists
// Generated by: scripts/generate-albums-data.js
// Total Images: 333
// Last Generated: 2026-02-21T16:14:51.659Z
// =====================

export interface AlbumImage {
  path: string;
  fileName: string;
  alt: string;
}

export interface AlbumConfig {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: string;
  coverImagePath: string | null;
  imageCount: number;
  images: AlbumImage[];
  isPrivate: boolean;
  createdAt: string;
}

// Get the image URL based on environment
export function getImageUrl(path: string): string {
  const baseUrl = process.env.NEXT_PUBLIC_IMAGE_BASE_URL || '/IvaDimitrovPhotos';
  return `${baseUrl}${path.startsWith('/') ? path : '/' + path}`;
}

// Get the thumbnail URL (for frontend display)
export function getThumbnailUrl(path: string): string {
  if (!path) return '/placeholder-album.jpg';
  const ext = path.substring(path.lastIndexOf('.'));
  const basePath = path.substring(0, path.lastIndexOf('.'));
  const thumbPath = `${basePath}_thumb${ext}`;
  return getImageUrl(thumbPath);
}

// Get the full image URL (for backend/lightbox)
export function getFullImageUrl(path: string): string {
  return getImageUrl(path);
}

export const albumsData: AlbumConfig[] = [
  {
    id: 'wedding-1',
    slug: 'wedding-1',
    title: 'Wedding 1',
    description: 'A beautiful wedding celebration captured in detail',
    category: 'Weddings',
    coverImagePath: '/Weddings/Wedding 1/small size/Album cover_thumb.jpg',
    imageCount: 31,
    images: [
      {
        path: '/Weddings/Wedding 1/small size/Album cover_thumb.jpg',
        fileName: 'Album cover_thumb.jpg',
        alt: 'Wedding 1 - Photo 1',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00215 - Copy_thumb.jpg',
        fileName: 'DSC00215 - Copy_thumb.jpg',
        alt: 'Wedding 1 - Photo 2',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00274_thumb.jpg',
        fileName: 'DSC00274_thumb.jpg',
        alt: 'Wedding 1 - Photo 3',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00425_thumb.jpg',
        fileName: 'DSC00425_thumb.jpg',
        alt: 'Wedding 1 - Photo 4',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00689_thumb.jpg',
        fileName: 'DSC00689_thumb.jpg',
        alt: 'Wedding 1 - Photo 5',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00739_thumb.jpg',
        fileName: 'DSC00739_thumb.jpg',
        alt: 'Wedding 1 - Photo 6',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC00829_thumb.jpg',
        fileName: 'DSC00829_thumb.jpg',
        alt: 'Wedding 1 - Photo 7',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC01234_thumb.jpg',
        fileName: 'DSC01234_thumb.jpg',
        alt: 'Wedding 1 - Photo 8',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08036_thumb.jpg',
        fileName: 'DSC08036_thumb.jpg',
        alt: 'Wedding 1 - Photo 9',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08048-2_thumb.jpg',
        fileName: 'DSC08048-2_thumb.jpg',
        alt: 'Wedding 1 - Photo 10',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08076_thumb.jpg',
        fileName: 'DSC08076_thumb.jpg',
        alt: 'Wedding 1 - Photo 11',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08114 - Copy_thumb.jpg',
        fileName: 'DSC08114 - Copy_thumb.jpg',
        alt: 'Wedding 1 - Photo 12',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08160_thumb.jpg',
        fileName: 'DSC08160_thumb.jpg',
        alt: 'Wedding 1 - Photo 13',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08246 - Copy_thumb.jpg',
        fileName: 'DSC08246 - Copy_thumb.jpg',
        alt: 'Wedding 1 - Photo 14',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08341_thumb.jpg',
        fileName: 'DSC08341_thumb.jpg',
        alt: 'Wedding 1 - Photo 15',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08380_thumb.jpg',
        fileName: 'DSC08380_thumb.jpg',
        alt: 'Wedding 1 - Photo 16',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08421_thumb.jpg',
        fileName: 'DSC08421_thumb.jpg',
        alt: 'Wedding 1 - Photo 17',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08528_thumb.jpg',
        fileName: 'DSC08528_thumb.jpg',
        alt: 'Wedding 1 - Photo 18',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08607_thumb.jpg',
        fileName: 'DSC08607_thumb.jpg',
        alt: 'Wedding 1 - Photo 19',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08757_thumb.jpg',
        fileName: 'DSC08757_thumb.jpg',
        alt: 'Wedding 1 - Photo 20',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08789_thumb.jpg',
        fileName: 'DSC08789_thumb.jpg',
        alt: 'Wedding 1 - Photo 21',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08875_thumb.jpg',
        fileName: 'DSC08875_thumb.jpg',
        alt: 'Wedding 1 - Photo 22',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08922-2-Edit_thumb.jpg',
        fileName: 'DSC08922-2-Edit_thumb.jpg',
        alt: 'Wedding 1 - Photo 23',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC08936-2_thumb.jpg',
        fileName: 'DSC08936-2_thumb.jpg',
        alt: 'Wedding 1 - Photo 24',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09025-2_thumb.jpg',
        fileName: 'DSC09025-2_thumb.jpg',
        alt: 'Wedding 1 - Photo 25',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09188-2_thumb.jpg',
        fileName: 'DSC09188-2_thumb.jpg',
        alt: 'Wedding 1 - Photo 26',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09224_thumb.jpg',
        fileName: 'DSC09224_thumb.jpg',
        alt: 'Wedding 1 - Photo 27',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09453_thumb.jpg',
        fileName: 'DSC09453_thumb.jpg',
        alt: 'Wedding 1 - Photo 28',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09613-Edit_thumb.jpg',
        fileName: 'DSC09613-Edit_thumb.jpg',
        alt: 'Wedding 1 - Photo 29',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09709_thumb.jpg',
        fileName: 'DSC09709_thumb.jpg',
        alt: 'Wedding 1 - Photo 30',
      },
      {
        path: '/Weddings/Wedding 1/small size/DSC09791_thumb.jpg',
        fileName: 'DSC09791_thumb.jpg',
        alt: 'Wedding 1 - Photo 31',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-21',
  },

  {
    id: 'wedding-2',
    slug: 'wedding-2',
    title: 'Wedding 2',
    description: 'An elegant wedding ceremony and reception',
    category: 'Weddings',
    coverImagePath: '/Weddings/Wedding 2/Album cover 2_thumb.jpg',
    imageCount: 19,
    images: [
      {
        path: '/Weddings/Wedding 2/Album cover 2_thumb.jpg',
        fileName: 'Album cover 2_thumb.jpg',
        alt: 'Wedding 2 - Photo 1',
      },
      {
        path: '/Weddings/Wedding 2/DSC04955-Edit-2_thumb.jpg',
        fileName: 'DSC04955-Edit-2_thumb.jpg',
        alt: 'Wedding 2 - Photo 2',
      },
      {
        path: '/Weddings/Wedding 2/DSC05002_thumb.jpg',
        fileName: 'DSC05002_thumb.jpg',
        alt: 'Wedding 2 - Photo 3',
      },
      {
        path: '/Weddings/Wedding 2/DSC05016_thumb.jpg',
        fileName: 'DSC05016_thumb.jpg',
        alt: 'Wedding 2 - Photo 4',
      },
      {
        path: '/Weddings/Wedding 2/DSC05030_thumb.jpg',
        fileName: 'DSC05030_thumb.jpg',
        alt: 'Wedding 2 - Photo 5',
      },
      {
        path: '/Weddings/Wedding 2/DSC05107-Edit-3_thumb.jpg',
        fileName: 'DSC05107-Edit-3_thumb.jpg',
        alt: 'Wedding 2 - Photo 6',
      },
      {
        path: '/Weddings/Wedding 2/DSC05118-Edit_thumb.jpg',
        fileName: 'DSC05118-Edit_thumb.jpg',
        alt: 'Wedding 2 - Photo 7',
      },
      {
        path: '/Weddings/Wedding 2/DSC05137_thumb.jpg',
        fileName: 'DSC05137_thumb.jpg',
        alt: 'Wedding 2 - Photo 8',
      },
      {
        path: '/Weddings/Wedding 2/DSC05145-2_thumb.jpg',
        fileName: 'DSC05145-2_thumb.jpg',
        alt: 'Wedding 2 - Photo 9',
      },
      {
        path: '/Weddings/Wedding 2/DSC05197_thumb.jpg',
        fileName: 'DSC05197_thumb.jpg',
        alt: 'Wedding 2 - Photo 10',
      },
      {
        path: '/Weddings/Wedding 2/DSC05207_thumb.jpg',
        fileName: 'DSC05207_thumb.jpg',
        alt: 'Wedding 2 - Photo 11',
      },
      {
        path: '/Weddings/Wedding 2/DSC05213_thumb.jpg',
        fileName: 'DSC05213_thumb.jpg',
        alt: 'Wedding 2 - Photo 12',
      },
      {
        path: '/Weddings/Wedding 2/DSC05214_thumb.jpg',
        fileName: 'DSC05214_thumb.jpg',
        alt: 'Wedding 2 - Photo 13',
      },
      {
        path: '/Weddings/Wedding 2/DSC05239_thumb.jpg',
        fileName: 'DSC05239_thumb.jpg',
        alt: 'Wedding 2 - Photo 14',
      },
      {
        path: '/Weddings/Wedding 2/DSC05272-2_thumb.jpg',
        fileName: 'DSC05272-2_thumb.jpg',
        alt: 'Wedding 2 - Photo 15',
      },
      {
        path: '/Weddings/Wedding 2/DSC05304_thumb.jpg',
        fileName: 'DSC05304_thumb.jpg',
        alt: 'Wedding 2 - Photo 16',
      },
      {
        path: '/Weddings/Wedding 2/DSC05309_thumb.jpg',
        fileName: 'DSC05309_thumb.jpg',
        alt: 'Wedding 2 - Photo 17',
      },
      {
        path: '/Weddings/Wedding 2/DSC05428_thumb.jpg',
        fileName: 'DSC05428_thumb.jpg',
        alt: 'Wedding 2 - Photo 18',
      },
      {
        path: '/Weddings/Wedding 2/DSC05497_thumb.jpg',
        fileName: 'DSC05497_thumb.jpg',
        alt: 'Wedding 2 - Photo 19',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-21',
  },

  {
    id: 'wedding-3',
    slug: 'wedding-3',
    title: 'Wedding 3',
    description: 'A romantic wedding captured throughout the day',
    category: 'Weddings',
    coverImagePath: '/Weddings/Wedding 3/Untitled Export/Album cover 3_thumb.jpg',
    imageCount: 14,
    images: [
      {
        path: '/Weddings/Wedding 3/Untitled Export/Album cover 3_thumb.jpg',
        fileName: 'Album cover 3_thumb.jpg',
        alt: 'Wedding 3 - Photo 1',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03199_thumb.jpg',
        fileName: 'DSC03199_thumb.jpg',
        alt: 'Wedding 3 - Photo 2',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03258_thumb.jpg',
        fileName: 'DSC03258_thumb.jpg',
        alt: 'Wedding 3 - Photo 3',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03347_thumb.jpg',
        fileName: 'DSC03347_thumb.jpg',
        alt: 'Wedding 3 - Photo 4',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03384_thumb.jpg',
        fileName: 'DSC03384_thumb.jpg',
        alt: 'Wedding 3 - Photo 5',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03562_thumb.jpg',
        fileName: 'DSC03562_thumb.jpg',
        alt: 'Wedding 3 - Photo 6',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03882_thumb.jpg',
        fileName: 'DSC03882_thumb.jpg',
        alt: 'Wedding 3 - Photo 7',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03911_thumb.jpg',
        fileName: 'DSC03911_thumb.jpg',
        alt: 'Wedding 3 - Photo 8',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC03955_thumb.jpg',
        fileName: 'DSC03955_thumb.jpg',
        alt: 'Wedding 3 - Photo 9',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC04017_thumb.jpg',
        fileName: 'DSC04017_thumb.jpg',
        alt: 'Wedding 3 - Photo 10',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/DSC04085_thumb.jpg',
        fileName: 'DSC04085_thumb.jpg',
        alt: 'Wedding 3 - Photo 11',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/wedding-ceremony-nottingham-groom-bride-portrait-belvoir-castle-flowers-happiness_thumb.jpg',
        fileName: 'wedding-ceremony-nottingham-groom-bride-portrait-belvoir-castle-flowers-happiness_thumb.jpg',
        alt: 'Wedding 3 - Photo 12',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/wedding-ceremony-nottingham-guests-portrait-belvoir-castle-flowers_thumb.jpg',
        fileName: 'wedding-ceremony-nottingham-guests-portrait-belvoir-castle-flowers_thumb.jpg',
        alt: 'Wedding 3 - Photo 13',
      },
      {
        path: '/Weddings/Wedding 3/Untitled Export/wedding-mother-of-bride-father-of-bride-ceremony-belvoir-castle_thumb.jpg',
        fileName: 'wedding-mother-of-bride-father-of-bride-ceremony-belvoir-castle_thumb.jpg',
        alt: 'Wedding 3 - Photo 14',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-21',
  },

  {
    id: 'engagement-session',
    slug: 'engagement-session',
    title: 'Engagement Session',
    description: 'Pre-wedding engagement photo session',
    category: 'Weddings',
    coverImagePath: '/Weddings/Engagement/Album cover eng_thumb.jpg',
    imageCount: 9,
    images: [
      {
        path: '/Weddings/Engagement/Album cover eng_thumb.jpg',
        fileName: 'Album cover eng_thumb.jpg',
        alt: 'Engagement Session - Photo 1',
      },
      {
        path: '/Weddings/Engagement/DSC06763_thumb.jpg',
        fileName: 'DSC06763_thumb.jpg',
        alt: 'Engagement Session - Photo 2',
      },
      {
        path: '/Weddings/Engagement/DSC06795_thumb.jpg',
        fileName: 'DSC06795_thumb.jpg',
        alt: 'Engagement Session - Photo 3',
      },
      {
        path: '/Weddings/Engagement/DSC06952_thumb.jpg',
        fileName: 'DSC06952_thumb.jpg',
        alt: 'Engagement Session - Photo 4',
      },
      {
        path: '/Weddings/Engagement/DSC07010-Edit_thumb.jpg',
        fileName: 'DSC07010-Edit_thumb.jpg',
        alt: 'Engagement Session - Photo 5',
      },
      {
        path: '/Weddings/Engagement/DSC07019_thumb.jpg',
        fileName: 'DSC07019_thumb.jpg',
        alt: 'Engagement Session - Photo 6',
      },
      {
        path: '/Weddings/Engagement/DSC07100_thumb.jpg',
        fileName: 'DSC07100_thumb.jpg',
        alt: 'Engagement Session - Photo 7',
      },
      {
        path: '/Weddings/Engagement/DSC07117_thumb.jpg',
        fileName: 'DSC07117_thumb.jpg',
        alt: 'Engagement Session - Photo 8',
      },
      {
        path: '/Weddings/Engagement/DSC07254-2_thumb.jpg',
        fileName: 'DSC07254-2_thumb.jpg',
        alt: 'Engagement Session - Photo 9',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-21',
  },

  {
    id: 'architecture-interiors',
    slug: 'architecture-interiors',
    title: 'Architecture & Interiors',
    description: 'Professional architectural and interior design photography',
    category: 'Architecture',
    coverImagePath: '/Architecture and Interiors small/DSC00293_thumb.jpg',
    imageCount: 31,
    images: [
      {
        path: '/Architecture and Interiors small/DSC00293_thumb.jpg',
        fileName: 'DSC00293_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 1',
      },
      {
        path: '/Architecture and Interiors small/DSC01126_thumb.jpg',
        fileName: 'DSC01126_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 2',
      },
      {
        path: '/Architecture and Interiors small/DSC01883_thumb.jpg',
        fileName: 'DSC01883_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 3',
      },
      {
        path: '/Architecture and Interiors small/DSC02274_thumb.jpg',
        fileName: 'DSC02274_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 4',
      },
      {
        path: '/Architecture and Interiors small/DSC02312_thumb.jpg',
        fileName: 'DSC02312_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 5',
      },
      {
        path: '/Architecture and Interiors small/DSC02461_thumb.jpg',
        fileName: 'DSC02461_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 6',
      },
      {
        path: '/Architecture and Interiors small/DSC02748-Edit_thumb.jpg',
        fileName: 'DSC02748-Edit_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 7',
      },
      {
        path: '/Architecture and Interiors small/DSC03379_thumb.jpg',
        fileName: 'DSC03379_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 8',
      },
      {
        path: '/Architecture and Interiors small/DSC03659_thumb.jpg',
        fileName: 'DSC03659_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 9',
      },
      {
        path: '/Architecture and Interiors small/DSC04340_thumb.jpg',
        fileName: 'DSC04340_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 10',
      },
      {
        path: '/Architecture and Interiors small/DSC05070-2_thumb.jpg',
        fileName: 'DSC05070-2_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 11',
      },
      {
        path: '/Architecture and Interiors small/DSC08906-HDR_thumb.jpg',
        fileName: 'DSC08906-HDR_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 12',
      },
      {
        path: '/Architecture and Interiors small/DSC08926-HDR_thumb.jpg',
        fileName: 'DSC08926-HDR_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 13',
      },
      {
        path: '/Architecture and Interiors small/DSC08976-HDR_thumb.jpg',
        fileName: 'DSC08976-HDR_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 14',
      },
      {
        path: '/Architecture and Interiors small/DSC09003-HDR_thumb.jpg',
        fileName: 'DSC09003-HDR_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 15',
      },
      {
        path: '/Architecture and Interiors small/DSC09018-HDR_thumb.jpg',
        fileName: 'DSC09018-HDR_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 16',
      },
      {
        path: '/Architecture and Interiors small/DSC09047-HDR_thumb.jpg',
        fileName: 'DSC09047-HDR_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 17',
      },
      {
        path: '/Architecture and Interiors small/DSC09084-HDR_thumb.jpg',
        fileName: 'DSC09084-HDR_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 18',
      },
      {
        path: '/Architecture and Interiors small/DSC09104-HDR_thumb.jpg',
        fileName: 'DSC09104-HDR_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 19',
      },
      {
        path: '/Architecture and Interiors small/DSC09261-HDR_thumb.jpg',
        fileName: 'DSC09261-HDR_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 20',
      },
      {
        path: '/Architecture and Interiors small/DSC09478-HDR-Edit_thumb.jpg',
        fileName: 'DSC09478-HDR-Edit_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 21',
      },
      {
        path: '/Architecture and Interiors small/DSC09507-HDR-Edit_thumb.jpg',
        fileName: 'DSC09507-HDR-Edit_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 22',
      },
      {
        path: '/Architecture and Interiors small/DSC09517-HDR-Edit_thumb.jpg',
        fileName: 'DSC09517-HDR-Edit_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 23',
      },
      {
        path: '/Architecture and Interiors small/DSC09527-HDR-Edit_thumb.jpg',
        fileName: 'DSC09527-HDR-Edit_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 24',
      },
      {
        path: '/Architecture and Interiors small/DSC09645-HDR_thumb.jpg',
        fileName: 'DSC09645-HDR_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 25',
      },
      {
        path: '/Architecture and Interiors small/DSC09665_thumb.jpg',
        fileName: 'DSC09665_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 26',
      },
      {
        path: '/Architecture and Interiors small/DSC09695-HDR-Edit-Edit_thumb.jpg',
        fileName: 'DSC09695-HDR-Edit-Edit_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 27',
      },
      {
        path: '/Architecture and Interiors small/DSC09728-HDR-Editqq_thumb.jpg',
        fileName: 'DSC09728-HDR-Editqq_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 28',
      },
      {
        path: '/Architecture and Interiors small/DSC09772_thumb.jpg',
        fileName: 'DSC09772_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 29',
      },
      {
        path: '/Architecture and Interiors small/DSC09854_thumb.jpg',
        fileName: 'DSC09854_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 30',
      },
      {
        path: '/Architecture and Interiors small/album Architecture and interiors cover_thumb.jpg',
        fileName: 'album Architecture and interiors cover_thumb.jpg',
        alt: 'Architecture & Interiors - Photo 31',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-21',
  },

  {
    id: 'branding',
    slug: 'branding',
    title: 'Branding',
    description: 'Corporate branding and product photography',
    category: 'Branding',
    coverImagePath: '/Branding small/album Branding cover_thumb.jpg',
    imageCount: 30,
    images: [
      {
        path: '/Branding small/DSC00179_thumb.jpg',
        fileName: 'DSC00179_thumb.jpg',
        alt: 'Branding - Photo 1',
      },
      {
        path: '/Branding small/DSC00193_thumb.jpg',
        fileName: 'DSC00193_thumb.jpg',
        alt: 'Branding - Photo 2',
      },
      {
        path: '/Branding small/DSC00254_thumb.jpg',
        fileName: 'DSC00254_thumb.jpg',
        alt: 'Branding - Photo 3',
      },
      {
        path: '/Branding small/DSC04901-Edit_thumb.jpg',
        fileName: 'DSC04901-Edit_thumb.jpg',
        alt: 'Branding - Photo 4',
      },
      {
        path: '/Branding small/DSC04920_thumb.jpg',
        fileName: 'DSC04920_thumb.jpg',
        alt: 'Branding - Photo 5',
      },
      {
        path: '/Branding small/DSC04932_thumb.jpg',
        fileName: 'DSC04932_thumb.jpg',
        alt: 'Branding - Photo 6',
      },
      {
        path: '/Branding small/DSC04948_thumb.jpg',
        fileName: 'DSC04948_thumb.jpg',
        alt: 'Branding - Photo 7',
      },
      {
        path: '/Branding small/DSC04987_thumb.jpg',
        fileName: 'DSC04987_thumb.jpg',
        alt: 'Branding - Photo 8',
      },
      {
        path: '/Branding small/DSC05042_thumb.jpg',
        fileName: 'DSC05042_thumb.jpg',
        alt: 'Branding - Photo 9',
      },
      {
        path: '/Branding small/DSC05097_thumb.jpg',
        fileName: 'DSC05097_thumb.jpg',
        alt: 'Branding - Photo 10',
      },
      {
        path: '/Branding small/DSC05124_thumb.jpg',
        fileName: 'DSC05124_thumb.jpg',
        alt: 'Branding - Photo 11',
      },
      {
        path: '/Branding small/DSC05253_thumb.jpg',
        fileName: 'DSC05253_thumb.jpg',
        alt: 'Branding - Photo 12',
      },
      {
        path: '/Branding small/DSC05268_thumb.jpg',
        fileName: 'DSC05268_thumb.jpg',
        alt: 'Branding - Photo 13',
      },
      {
        path: '/Branding small/DSC05319_thumb.jpg',
        fileName: 'DSC05319_thumb.jpg',
        alt: 'Branding - Photo 14',
      },
      {
        path: '/Branding small/DSC05476_thumb.jpg',
        fileName: 'DSC05476_thumb.jpg',
        alt: 'Branding - Photo 15',
      },
      {
        path: '/Branding small/DSC07238_thumb.jpg',
        fileName: 'DSC07238_thumb.jpg',
        alt: 'Branding - Photo 16',
      },
      {
        path: '/Branding small/DSC07247_thumb.jpg',
        fileName: 'DSC07247_thumb.jpg',
        alt: 'Branding - Photo 17',
      },
      {
        path: '/Branding small/DSC07250_thumb.jpg',
        fileName: 'DSC07250_thumb.jpg',
        alt: 'Branding - Photo 18',
      },
      {
        path: '/Branding small/DSC07264-Edit_thumb.jpg',
        fileName: 'DSC07264-Edit_thumb.jpg',
        alt: 'Branding - Photo 19',
      },
      {
        path: '/Branding small/DSC07281_thumb.jpg',
        fileName: 'DSC07281_thumb.jpg',
        alt: 'Branding - Photo 20',
      },
      {
        path: '/Branding small/DSC07328_thumb.jpg',
        fileName: 'DSC07328_thumb.jpg',
        alt: 'Branding - Photo 21',
      },
      {
        path: '/Branding small/DSC07353_thumb.jpg',
        fileName: 'DSC07353_thumb.jpg',
        alt: 'Branding - Photo 22',
      },
      {
        path: '/Branding small/DSC07358_thumb.jpg',
        fileName: 'DSC07358_thumb.jpg',
        alt: 'Branding - Photo 23',
      },
      {
        path: '/Branding small/DSC07385_thumb.jpg',
        fileName: 'DSC07385_thumb.jpg',
        alt: 'Branding - Photo 24',
      },
      {
        path: '/Branding small/DSC07385s_thumb.jpg',
        fileName: 'DSC07385s_thumb.jpg',
        alt: 'Branding - Photo 25',
      },
      {
        path: '/Branding small/DSC07497_thumb.jpg',
        fileName: 'DSC07497_thumb.jpg',
        alt: 'Branding - Photo 26',
      },
      {
        path: '/Branding small/DSC07517_thumb.jpg',
        fileName: 'DSC07517_thumb.jpg',
        alt: 'Branding - Photo 27',
      },
      {
        path: '/Branding small/DSC07664_thumb.jpg',
        fileName: 'DSC07664_thumb.jpg',
        alt: 'Branding - Photo 28',
      },
      {
        path: '/Branding small/album Branding cover_thumb.jpg',
        fileName: 'album Branding cover_thumb.jpg',
        alt: 'Branding - Photo 29',
      },
      {
        path: '/Branding small/qDSC00300_thumb.jpg',
        fileName: 'qDSC00300_thumb.jpg',
        alt: 'Branding - Photo 30',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-21',
  },

  {
    id: 'children-family',
    slug: 'children-family',
    title: 'Children & Family',
    description: 'Heartwarming family and children photography',
    category: 'Family',
    coverImagePath: '/Children and family/Album cover kids_thumb.jpg',
    imageCount: 100,
    images: [
      {
        path: '/Children and family/Album cover kids_thumb.jpg',
        fileName: 'Album cover kids_thumb.jpg',
        alt: 'Children & Family - Photo 1',
      },
      {
        path: '/Children and family/DSC00120_thumb.jpg',
        fileName: 'DSC00120_thumb.jpg',
        alt: 'Children & Family - Photo 2',
      },
      {
        path: '/Children and family/DSC00583_thumb.jpg',
        fileName: 'DSC00583_thumb.jpg',
        alt: 'Children & Family - Photo 3',
      },
      {
        path: '/Children and family/DSC00715-Edit_thumb.jpg',
        fileName: 'DSC00715-Edit_thumb.jpg',
        alt: 'Children & Family - Photo 4',
      },
      {
        path: '/Children and family/DSC01297_thumb.jpg',
        fileName: 'DSC01297_thumb.jpg',
        alt: 'Children & Family - Photo 5',
      },
      {
        path: '/Children and family/DSC01320_thumb.jpg',
        fileName: 'DSC01320_thumb.jpg',
        alt: 'Children & Family - Photo 6',
      },
      {
        path: '/Children and family/DSC01529_thumb.jpg',
        fileName: 'DSC01529_thumb.jpg',
        alt: 'Children & Family - Photo 7',
      },
      {
        path: '/Children and family/DSC01690_thumb.jpg',
        fileName: 'DSC01690_thumb.jpg',
        alt: 'Children & Family - Photo 8',
      },
      {
        path: '/Children and family/DSC01979_thumb.jpg',
        fileName: 'DSC01979_thumb.jpg',
        alt: 'Children & Family - Photo 9',
      },
      {
        path: '/Children and family/DSC02103_thumb.jpg',
        fileName: 'DSC02103_thumb.jpg',
        alt: 'Children & Family - Photo 10',
      },
      {
        path: '/Children and family/DSC02247_thumb.jpg',
        fileName: 'DSC02247_thumb.jpg',
        alt: 'Children & Family - Photo 11',
      },
      {
        path: '/Children and family/DSC02490_thumb.jpg',
        fileName: 'DSC02490_thumb.jpg',
        alt: 'Children & Family - Photo 12',
      },
      {
        path: '/Children and family/DSC02611_thumb.jpg',
        fileName: 'DSC02611_thumb.jpg',
        alt: 'Children & Family - Photo 13',
      },
      {
        path: '/Children and family/DSC02659-Edit-2_thumb.jpg',
        fileName: 'DSC02659-Edit-2_thumb.jpg',
        alt: 'Children & Family - Photo 14',
      },
      {
        path: '/Children and family/DSC02676_thumb.jpg',
        fileName: 'DSC02676_thumb.jpg',
        alt: 'Children & Family - Photo 15',
      },
      {
        path: '/Children and family/DSC02758_thumb.jpg',
        fileName: 'DSC02758_thumb.jpg',
        alt: 'Children & Family - Photo 16',
      },
      {
        path: '/Children and family/DSC02899_thumb.jpg',
        fileName: 'DSC02899_thumb.jpg',
        alt: 'Children & Family - Photo 17',
      },
      {
        path: '/Children and family/DSC02941_thumb.jpg',
        fileName: 'DSC02941_thumb.jpg',
        alt: 'Children & Family - Photo 18',
      },
      {
        path: '/Children and family/DSC03065-Edit_thumb.jpg',
        fileName: 'DSC03065-Edit_thumb.jpg',
        alt: 'Children & Family - Photo 19',
      },
      {
        path: '/Children and family/DSC03259-Edit_thumb.jpg',
        fileName: 'DSC03259-Edit_thumb.jpg',
        alt: 'Children & Family - Photo 20',
      },
      {
        path: '/Children and family/DSC03271_thumb.jpg',
        fileName: 'DSC03271_thumb.jpg',
        alt: 'Children & Family - Photo 21',
      },
      {
        path: '/Children and family/DSC03299_thumb.jpg',
        fileName: 'DSC03299_thumb.jpg',
        alt: 'Children & Family - Photo 22',
      },
      {
        path: '/Children and family/DSC03319-Edit_thumb.jpg',
        fileName: 'DSC03319-Edit_thumb.jpg',
        alt: 'Children & Family - Photo 23',
      },
      {
        path: '/Children and family/DSC03355-Edit_thumb.jpg',
        fileName: 'DSC03355-Edit_thumb.jpg',
        alt: 'Children & Family - Photo 24',
      },
      {
        path: '/Children and family/DSC03432_thumb.jpg',
        fileName: 'DSC03432_thumb.jpg',
        alt: 'Children & Family - Photo 25',
      },
      {
        path: '/Children and family/DSC03437_thumb.jpg',
        fileName: 'DSC03437_thumb.jpg',
        alt: 'Children & Family - Photo 26',
      },
      {
        path: '/Children and family/DSC03449_thumb.jpg',
        fileName: 'DSC03449_thumb.jpg',
        alt: 'Children & Family - Photo 27',
      },
      {
        path: '/Children and family/DSC03450_thumb.jpg',
        fileName: 'DSC03450_thumb.jpg',
        alt: 'Children & Family - Photo 28',
      },
      {
        path: '/Children and family/DSC03456-Edit_thumb.jpg',
        fileName: 'DSC03456-Edit_thumb.jpg',
        alt: 'Children & Family - Photo 29',
      },
      {
        path: '/Children and family/DSC03586-2_thumb.jpg',
        fileName: 'DSC03586-2_thumb.jpg',
        alt: 'Children & Family - Photo 30',
      },
      {
        path: '/Children and family/DSC03657_thumb.jpg',
        fileName: 'DSC03657_thumb.jpg',
        alt: 'Children & Family - Photo 31',
      },
      {
        path: '/Children and family/DSC03708_thumb.jpg',
        fileName: 'DSC03708_thumb.jpg',
        alt: 'Children & Family - Photo 32',
      },
      {
        path: '/Children and family/DSC03716_thumb.jpg',
        fileName: 'DSC03716_thumb.jpg',
        alt: 'Children & Family - Photo 33',
      },
      {
        path: '/Children and family/DSC03823_thumb.jpg',
        fileName: 'DSC03823_thumb.jpg',
        alt: 'Children & Family - Photo 34',
      },
      {
        path: '/Children and family/DSC03858_thumb.jpg',
        fileName: 'DSC03858_thumb.jpg',
        alt: 'Children & Family - Photo 35',
      },
      {
        path: '/Children and family/DSC03898_thumb.jpg',
        fileName: 'DSC03898_thumb.jpg',
        alt: 'Children & Family - Photo 36',
      },
      {
        path: '/Children and family/DSC039611_thumb.jpg',
        fileName: 'DSC039611_thumb.jpg',
        alt: 'Children & Family - Photo 37',
      },
      {
        path: '/Children and family/DSC03993-2_thumb.jpg',
        fileName: 'DSC03993-2_thumb.jpg',
        alt: 'Children & Family - Photo 38',
      },
      {
        path: '/Children and family/DSC04390dd_thumb.jpg',
        fileName: 'DSC04390dd_thumb.jpg',
        alt: 'Children & Family - Photo 39',
      },
      {
        path: '/Children and family/DSC04446-2_thumb.jpg',
        fileName: 'DSC04446-2_thumb.jpg',
        alt: 'Children & Family - Photo 40',
      },
      {
        path: '/Children and family/DSC04829-Edit_thumb.jpg',
        fileName: 'DSC04829-Edit_thumb.jpg',
        alt: 'Children & Family - Photo 41',
      },
      {
        path: '/Children and family/DSC05146-Edit-Edit-2_thumb.jpg',
        fileName: 'DSC05146-Edit-Edit-2_thumb.jpg',
        alt: 'Children & Family - Photo 42',
      },
      {
        path: '/Children and family/DSC05346_thumb.jpg',
        fileName: 'DSC05346_thumb.jpg',
        alt: 'Children & Family - Photo 43',
      },
      {
        path: '/Children and family/DSC05378_thumb.jpg',
        fileName: 'DSC05378_thumb.jpg',
        alt: 'Children & Family - Photo 44',
      },
      {
        path: '/Children and family/DSC05403_thumb.jpg',
        fileName: 'DSC05403_thumb.jpg',
        alt: 'Children & Family - Photo 45',
      },
      {
        path: '/Children and family/DSC05422_thumb.jpg',
        fileName: 'DSC05422_thumb.jpg',
        alt: 'Children & Family - Photo 46',
      },
      {
        path: '/Children and family/DSC05451_thumb.jpg',
        fileName: 'DSC05451_thumb.jpg',
        alt: 'Children & Family - Photo 47',
      },
      {
        path: '/Children and family/DSC05639_thumb.jpg',
        fileName: 'DSC05639_thumb.jpg',
        alt: 'Children & Family - Photo 48',
      },
      {
        path: '/Children and family/DSC05670_thumb.jpg',
        fileName: 'DSC05670_thumb.jpg',
        alt: 'Children & Family - Photo 49',
      },
      {
        path: '/Children and family/DSC05711_thumb.jpg',
        fileName: 'DSC05711_thumb.jpg',
        alt: 'Children & Family - Photo 50',
      },
      {
        path: '/Children and family/DSC05809-Edit_thumb.jpg',
        fileName: 'DSC05809-Edit_thumb.jpg',
        alt: 'Children & Family - Photo 51',
      },
      {
        path: '/Children and family/DSC05966_thumb.jpg',
        fileName: 'DSC05966_thumb.jpg',
        alt: 'Children & Family - Photo 52',
      },
      {
        path: '/Children and family/DSC05992_thumb.jpg',
        fileName: 'DSC05992_thumb.jpg',
        alt: 'Children & Family - Photo 53',
      },
      {
        path: '/Children and family/DSC06030_thumb.jpg',
        fileName: 'DSC06030_thumb.jpg',
        alt: 'Children & Family - Photo 54',
      },
      {
        path: '/Children and family/DSC06082_thumb.jpg',
        fileName: 'DSC06082_thumb.jpg',
        alt: 'Children & Family - Photo 55',
      },
      {
        path: '/Children and family/DSC06140_thumb.jpg',
        fileName: 'DSC06140_thumb.jpg',
        alt: 'Children & Family - Photo 56',
      },
      {
        path: '/Children and family/DSC06233_thumb.jpg',
        fileName: 'DSC06233_thumb.jpg',
        alt: 'Children & Family - Photo 57',
      },
      {
        path: '/Children and family/DSC06375_thumb.jpg',
        fileName: 'DSC06375_thumb.jpg',
        alt: 'Children & Family - Photo 58',
      },
      {
        path: '/Children and family/DSC06417_thumb.jpg',
        fileName: 'DSC06417_thumb.jpg',
        alt: 'Children & Family - Photo 59',
      },
      {
        path: '/Children and family/DSC06435_thumb.jpg',
        fileName: 'DSC06435_thumb.jpg',
        alt: 'Children & Family - Photo 60',
      },
      {
        path: '/Children and family/DSC06661_thumb.jpg',
        fileName: 'DSC06661_thumb.jpg',
        alt: 'Children & Family - Photo 61',
      },
      {
        path: '/Children and family/DSC07134_thumb.jpg',
        fileName: 'DSC07134_thumb.jpg',
        alt: 'Children & Family - Photo 62',
      },
      {
        path: '/Children and family/DSC07713-Enhanced-NR-5_thumb.jpg',
        fileName: 'DSC07713-Enhanced-NR-5_thumb.jpg',
        alt: 'Children & Family - Photo 63',
      },
      {
        path: '/Children and family/DSC08159_thumb.jpg',
        fileName: 'DSC08159_thumb.jpg',
        alt: 'Children & Family - Photo 64',
      },
      {
        path: '/Children and family/DSC08450-Editwe_thumb.jpg',
        fileName: 'DSC08450-Editwe_thumb.jpg',
        alt: 'Children & Family - Photo 65',
      },
      {
        path: '/Children and family/DSC0863522_thumb.jpg',
        fileName: 'DSC0863522_thumb.jpg',
        alt: 'Children & Family - Photo 66',
      },
      {
        path: '/Children and family/DSC08649_thumb.jpg',
        fileName: 'DSC08649_thumb.jpg',
        alt: 'Children & Family - Photo 67',
      },
      {
        path: '/Children and family/DSC08715_thumb.jpg',
        fileName: 'DSC08715_thumb.jpg',
        alt: 'Children & Family - Photo 68',
      },
      {
        path: '/Children and family/DSC08725_thumb.jpg',
        fileName: 'DSC08725_thumb.jpg',
        alt: 'Children & Family - Photo 69',
      },
      {
        path: '/Children and family/DSC09299_thumb.jpg',
        fileName: 'DSC09299_thumb.jpg',
        alt: 'Children & Family - Photo 70',
      },
      {
        path: '/Children and family/DSC09517-Edit1_thumb.jpg',
        fileName: 'DSC09517-Edit1_thumb.jpg',
        alt: 'Children & Family - Photo 71',
      },
      {
        path: '/Children and family/DSC09613_thumb.jpg',
        fileName: 'DSC09613_thumb.jpg',
        alt: 'Children & Family - Photo 72',
      },
      {
        path: '/Children and family/DSC09776_thumb.jpg',
        fileName: 'DSC09776_thumb.jpg',
        alt: 'Children & Family - Photo 73',
      },
      {
        path: '/Children and family/DSC09811_thumb.jpg',
        fileName: 'DSC09811_thumb.jpg',
        alt: 'Children & Family - Photo 74',
      },
      {
        path: '/Children and family/Kid-portrait-nottingham-book_thumb.jpg',
        fileName: 'Kid-portrait-nottingham-book_thumb.jpg',
        alt: 'Children & Family - Photo 75',
      },
      {
        path: '/Children and family/Kid-portrait-nottingham-journey-life-photography_thumb.jpg',
        fileName: 'Kid-portrait-nottingham-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 76',
      },
      {
        path: '/Children and family/baby-and-daddy-portrait-beautiful-blue-eyes-nottingham-photographer_thumb.jpg',
        fileName: 'baby-and-daddy-portrait-beautiful-blue-eyes-nottingham-photographer_thumb.jpg',
        alt: 'Children & Family - Photo 77',
      },
      {
        path: '/Children and family/boy-child-portrait-nottingham-journey-life-photography_thumb.jpg',
        fileName: 'boy-child-portrait-nottingham-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 78',
      },
      {
        path: '/Children and family/boy-with-daisies-spring-family-photoshoots-nottingham.jpg',
        fileName: 'boy-with-daisies-spring-family-photoshoots-nottingham.jpg',
        alt: 'Children & Family - Photo 79',
      },
      {
        path: '/Children and family/boy-with-daisies-spring-family-photoshoots-nottingham_thumb.jpg',
        fileName: 'boy-with-daisies-spring-family-photoshoots-nottingham_thumb.jpg',
        alt: 'Children & Family - Photo 80',
      },
      {
        path: '/Children and family/child-christening-birthday-party-portrait-family-photoshoot-journey-life-photography-girl-on-a-swing-nottingham_thumb.jpg',
        fileName: 'child-christening-birthday-party-portrait-family-photoshoot-journey-life-photography-girl-on-a-swing-nottingham_thumb.jpg',
        alt: 'Children & Family - Photo 81',
      },
      {
        path: '/Children and family/child-christening-portrait-family-photoshoot-journey-life-photography_thumb.jpg',
        fileName: 'child-christening-portrait-family-photoshoot-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 82',
      },
      {
        path: '/Children and family/child-first-birthday-party-portrait-family-photoshoot-cake-journey-life-photography_thumb.jpg',
        fileName: 'child-first-birthday-party-portrait-family-photoshoot-cake-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 83',
      },
      {
        path: '/Children and family/child-first-birthday-party-portrait-family-photoshoot-cake-smash-journey-life-photography-event-nottingham_thumb.jpg',
        fileName: 'child-first-birthday-party-portrait-family-photoshoot-cake-smash-journey-life-photography-event-nottingham_thumb.jpg',
        alt: 'Children & Family - Photo 84',
      },
      {
        path: '/Children and family/child-first-birthday-party-portrait-family-photoshoot-journey-life-photography_thumb.jpg',
        fileName: 'child-first-birthday-party-portrait-family-photoshoot-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 85',
      },
      {
        path: '/Children and family/child-jump-gymnastics-portrait-nottingham-journey-life-photography_thumb.jpg',
        fileName: 'child-jump-gymnastics-portrait-nottingham-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 86',
      },
      {
        path: '/Children and family/child-portrait-nottingham-journey-life-photography_thumb.jpg',
        fileName: 'child-portrait-nottingham-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 87',
      },
      {
        path: '/Children and family/child-read-book-portrait-nottingham-journey-life-photography_thumb.jpg',
        fileName: 'child-read-book-portrait-nottingham-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 88',
      },
      {
        path: '/Children and family/child-smiley-portrait-nottingham-birthday-party_thumb.jpg',
        fileName: 'child-smiley-portrait-nottingham-birthday-party_thumb.jpg',
        alt: 'Children & Family - Photo 89',
      },
      {
        path: '/Children and family/child-smiley-portrait-nottingham_thumb.jpg',
        fileName: 'child-smiley-portrait-nottingham_thumb.jpg',
        alt: 'Children & Family - Photo 90',
      },
      {
        path: '/Children and family/crossfit-kids-portraits-sports-happy-kids-photography-journey-life-photography-smiles_thumb.jpg',
        fileName: 'crossfit-kids-portraits-sports-happy-kids-photography-journey-life-photography-smiles_thumb.jpg',
        alt: 'Children & Family - Photo 91',
      },
      {
        path: '/Children and family/crossfit-kids-portraits-sports-photography-journey-life-photography-smiles_thumb.jpg',
        fileName: 'crossfit-kids-portraits-sports-photography-journey-life-photography-smiles_thumb.jpg',
        alt: 'Children & Family - Photo 92',
      },
      {
        path: '/Children and family/girl-funky-portrait-nottingham-journey-life-photography_thumb.jpg',
        fileName: 'girl-funky-portrait-nottingham-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 93',
      },
      {
        path: '/Children and family/girl-portrait-autumn-nottingham-beautiful-journey-life-photography_thumb.jpg',
        fileName: 'girl-portrait-autumn-nottingham-beautiful-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 94',
      },
      {
        path: '/Children and family/girl-portrait-dovedale-nottingham-beautiful-journey-life-photography_thumb.jpg',
        fileName: 'girl-portrait-dovedale-nottingham-beautiful-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 95',
      },
      {
        path: '/Children and family/girl-portrait-playground-party-nottingham-beautiful-journey-life-photography_thumb.jpg',
        fileName: 'girl-portrait-playground-party-nottingham-beautiful-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 96',
      },
      {
        path: '/Children and family/interesting-portrait-of-a-child-smiley-portrait-nottingham_thumb.jpg',
        fileName: 'interesting-portrait-of-a-child-smiley-portrait-nottingham_thumb.jpg',
        alt: 'Children & Family - Photo 97',
      },
      {
        path: '/Children and family/kid-portrait-bluebell-forest-nottingham-journey-life-photography-woods-flowers_thumb.jpg',
        fileName: 'kid-portrait-bluebell-forest-nottingham-journey-life-photography-woods-flowers_thumb.jpg',
        alt: 'Children & Family - Photo 98',
      },
      {
        path: '/Children and family/kids-different-portrait-shadows-and-light-journey-life-photography-nottingham_thumb.jpg',
        fileName: 'kids-different-portrait-shadows-and-light-journey-life-photography-nottingham_thumb.jpg',
        alt: 'Children & Family - Photo 99',
      },
      {
        path: '/Children and family/wild-garlic-portrait-girl-nottingham-woods-nature-forest-journey-life-photography_thumb.jpg',
        fileName: 'wild-garlic-portrait-girl-nottingham-woods-nature-forest-journey-life-photography_thumb.jpg',
        alt: 'Children & Family - Photo 100',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-21',
  },

  {
    id: 'corporate-events',
    slug: 'corporate-events',
    title: 'Corporate Events',
    description: 'Professional corporate event photography',
    category: 'Corporate',
    coverImagePath: '/Corporate small/Album cover_thumb.jpg',
    imageCount: 17,
    images: [
      {
        path: '/Corporate small/Album cover_thumb.jpg',
        fileName: 'Album cover_thumb.jpg',
        alt: 'Corporate Events - Photo 1',
      },
      {
        path: '/Corporate small/BW DSC09218-Edit-2_thumb.jpg',
        fileName: 'BW DSC09218-Edit-2_thumb.jpg',
        alt: 'Corporate Events - Photo 2',
      },
      {
        path: '/Corporate small/BW DSC09238-Edit-2-2_thumb.jpg',
        fileName: 'BW DSC09238-Edit-2-2_thumb.jpg',
        alt: 'Corporate Events - Photo 3',
      },
      {
        path: '/Corporate small/BW DSC09339-Edit-2_thumb.jpg',
        fileName: 'BW DSC09339-Edit-2_thumb.jpg',
        alt: 'Corporate Events - Photo 4',
      },
      {
        path: '/Corporate small/DSC03731-Edit_thumb.jpg',
        fileName: 'DSC03731-Edit_thumb.jpg',
        alt: 'Corporate Events - Photo 5',
      },
      {
        path: '/Corporate small/DSC03799-Edit-3_thumb.jpg',
        fileName: 'DSC03799-Edit-3_thumb.jpg',
        alt: 'Corporate Events - Photo 6',
      },
      {
        path: '/Corporate small/DSC03816-Edit-Edit-2_thumb.jpg',
        fileName: 'DSC03816-Edit-Edit-2_thumb.jpg',
        alt: 'Corporate Events - Photo 7',
      },
      {
        path: '/Corporate small/DSC03868-Edit_thumb.jpg',
        fileName: 'DSC03868-Edit_thumb.jpg',
        alt: 'Corporate Events - Photo 8',
      },
      {
        path: '/Corporate small/DSC04059-Edit_thumb.jpg',
        fileName: 'DSC04059-Edit_thumb.jpg',
        alt: 'Corporate Events - Photo 9',
      },
      {
        path: '/Corporate small/DSC05752_thumb.jpg',
        fileName: 'DSC05752_thumb.jpg',
        alt: 'Corporate Events - Photo 10',
      },
      {
        path: '/Corporate small/DSC05787_thumb.jpg',
        fileName: 'DSC05787_thumb.jpg',
        alt: 'Corporate Events - Photo 11',
      },
      {
        path: '/Corporate small/DSC05846_thumb.jpg',
        fileName: 'DSC05846_thumb.jpg',
        alt: 'Corporate Events - Photo 12',
      },
      {
        path: '/Corporate small/DSC05924_thumb.jpg',
        fileName: 'DSC05924_thumb.jpg',
        alt: 'Corporate Events - Photo 13',
      },
      {
        path: '/Corporate small/DSC05987_thumb.jpg',
        fileName: 'DSC05987_thumb.jpg',
        alt: 'Corporate Events - Photo 14',
      },
      {
        path: '/Corporate small/DSC06078_(2)_thumb.jpg',
        fileName: 'DSC06078_(2)_thumb.jpg',
        alt: 'Corporate Events - Photo 15',
      },
      {
        path: '/Corporate small/DSC06224_thumb.jpg',
        fileName: 'DSC06224_thumb.jpg',
        alt: 'Corporate Events - Photo 16',
      },
      {
        path: '/Corporate small/DSC09256-Edit-2-Edit M_thumb.jpg',
        fileName: 'DSC09256-Edit-2-Edit M_thumb.jpg',
        alt: 'Corporate Events - Photo 17',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-21',
  },

  {
    id: 'travel-photography',
    slug: 'travel-photography',
    title: 'Travel Photography',
    description: 'Travel and adventure photography from around the world',
    category: 'Travel',
    coverImagePath: '/Travel small/Albu cover travel_thumb.jpg',
    imageCount: 57,
    images: [
      {
        path: '/Travel small/Albu cover travel_thumb.jpg',
        fileName: 'Albu cover travel_thumb.jpg',
        alt: 'Travel Photography - Photo 1',
      },
      {
        path: '/Travel small/DSC00018_thumb.jpg',
        fileName: 'DSC00018_thumb.jpg',
        alt: 'Travel Photography - Photo 2',
      },
      {
        path: '/Travel small/DSC00710_thumb.jpg',
        fileName: 'DSC00710_thumb.jpg',
        alt: 'Travel Photography - Photo 3',
      },
      {
        path: '/Travel small/DSC00722_thumb.jpg',
        fileName: 'DSC00722_thumb.jpg',
        alt: 'Travel Photography - Photo 4',
      },
      {
        path: '/Travel small/DSC00800_thumb.jpg',
        fileName: 'DSC00800_thumb.jpg',
        alt: 'Travel Photography - Photo 5',
      },
      {
        path: '/Travel small/DSC00818-2_thumb.jpg',
        fileName: 'DSC00818-2_thumb.jpg',
        alt: 'Travel Photography - Photo 6',
      },
      {
        path: '/Travel small/DSC00842_thumb.jpg',
        fileName: 'DSC00842_thumb.jpg',
        alt: 'Travel Photography - Photo 7',
      },
      {
        path: '/Travel small/DSC01104_thumb.jpg',
        fileName: 'DSC01104_thumb.jpg',
        alt: 'Travel Photography - Photo 8',
      },
      {
        path: '/Travel small/DSC01207_thumb.jpg',
        fileName: 'DSC01207_thumb.jpg',
        alt: 'Travel Photography - Photo 9',
      },
      {
        path: '/Travel small/DSC01618_thumb.jpg',
        fileName: 'DSC01618_thumb.jpg',
        alt: 'Travel Photography - Photo 10',
      },
      {
        path: '/Travel small/DSC01759_thumb.jpg',
        fileName: 'DSC01759_thumb.jpg',
        alt: 'Travel Photography - Photo 11',
      },
      {
        path: '/Travel small/DSC01943_thumb.jpg',
        fileName: 'DSC01943_thumb.jpg',
        alt: 'Travel Photography - Photo 12',
      },
      {
        path: '/Travel small/DSC02023_thumb.jpg',
        fileName: 'DSC02023_thumb.jpg',
        alt: 'Travel Photography - Photo 13',
      },
      {
        path: '/Travel small/DSC02464_thumb.jpg',
        fileName: 'DSC02464_thumb.jpg',
        alt: 'Travel Photography - Photo 14',
      },
      {
        path: '/Travel small/DSC02472_thumb.jpg',
        fileName: 'DSC02472_thumb.jpg',
        alt: 'Travel Photography - Photo 15',
      },
      {
        path: '/Travel small/DSC02741_thumb.jpg',
        fileName: 'DSC02741_thumb.jpg',
        alt: 'Travel Photography - Photo 16',
      },
      {
        path: '/Travel small/DSC02881-Edit-4_thumb.jpg',
        fileName: 'DSC02881-Edit-4_thumb.jpg',
        alt: 'Travel Photography - Photo 17',
      },
      {
        path: '/Travel small/DSC03015_thumb.jpg',
        fileName: 'DSC03015_thumb.jpg',
        alt: 'Travel Photography - Photo 18',
      },
      {
        path: '/Travel small/DSC03376-2_thumb.jpg',
        fileName: 'DSC03376-2_thumb.jpg',
        alt: 'Travel Photography - Photo 19',
      },
      {
        path: '/Travel small/DSC03451_thumb.jpg',
        fileName: 'DSC03451_thumb.jpg',
        alt: 'Travel Photography - Photo 20',
      },
      {
        path: '/Travel small/DSC03777_thumb.jpg',
        fileName: 'DSC03777_thumb.jpg',
        alt: 'Travel Photography - Photo 21',
      },
      {
        path: '/Travel small/DSC03995-4_thumb.jpg',
        fileName: 'DSC03995-4_thumb.jpg',
        alt: 'Travel Photography - Photo 22',
      },
      {
        path: '/Travel small/DSC03995-5_thumb.jpg',
        fileName: 'DSC03995-5_thumb.jpg',
        alt: 'Travel Photography - Photo 23',
      },
      {
        path: '/Travel small/DSC04033-3_thumb.jpg',
        fileName: 'DSC04033-3_thumb.jpg',
        alt: 'Travel Photography - Photo 24',
      },
      {
        path: '/Travel small/DSC04311_thumb.jpg',
        fileName: 'DSC04311_thumb.jpg',
        alt: 'Travel Photography - Photo 25',
      },
      {
        path: '/Travel small/DSC04379-2_thumb.jpg',
        fileName: 'DSC04379-2_thumb.jpg',
        alt: 'Travel Photography - Photo 26',
      },
      {
        path: '/Travel small/DSC04813_thumb.jpg',
        fileName: 'DSC04813_thumb.jpg',
        alt: 'Travel Photography - Photo 27',
      },
      {
        path: '/Travel small/DSC04946-Edit_thumb.jpg',
        fileName: 'DSC04946-Edit_thumb.jpg',
        alt: 'Travel Photography - Photo 28',
      },
      {
        path: '/Travel small/DSC04964_thumb.jpg',
        fileName: 'DSC04964_thumb.jpg',
        alt: 'Travel Photography - Photo 29',
      },
      {
        path: '/Travel small/DSC05040_thumb.jpg',
        fileName: 'DSC05040_thumb.jpg',
        alt: 'Travel Photography - Photo 30',
      },
      {
        path: '/Travel small/DSC05043_thumb.jpg',
        fileName: 'DSC05043_thumb.jpg',
        alt: 'Travel Photography - Photo 31',
      },
      {
        path: '/Travel small/DSC05083_thumb.jpg',
        fileName: 'DSC05083_thumb.jpg',
        alt: 'Travel Photography - Photo 32',
      },
      {
        path: '/Travel small/DSC05338-Edit_thumb.jpg',
        fileName: 'DSC05338-Edit_thumb.jpg',
        alt: 'Travel Photography - Photo 33',
      },
      {
        path: '/Travel small/DSC05807_thumb.jpg',
        fileName: 'DSC05807_thumb.jpg',
        alt: 'Travel Photography - Photo 34',
      },
      {
        path: '/Travel small/DSC06115-Edit_thumb.jpg',
        fileName: 'DSC06115-Edit_thumb.jpg',
        alt: 'Travel Photography - Photo 35',
      },
      {
        path: '/Travel small/DSC06290_thumb.jpg',
        fileName: 'DSC06290_thumb.jpg',
        alt: 'Travel Photography - Photo 36',
      },
      {
        path: '/Travel small/DSC06394-Edit_thumb.jpg',
        fileName: 'DSC06394-Edit_thumb.jpg',
        alt: 'Travel Photography - Photo 37',
      },
      {
        path: '/Travel small/DSC06399-Edit_thumb.jpg',
        fileName: 'DSC06399-Edit_thumb.jpg',
        alt: 'Travel Photography - Photo 38',
      },
      {
        path: '/Travel small/DSC06427_thumb.jpg',
        fileName: 'DSC06427_thumb.jpg',
        alt: 'Travel Photography - Photo 39',
      },
      {
        path: '/Travel small/DSC06456_thumb.jpg',
        fileName: 'DSC06456_thumb.jpg',
        alt: 'Travel Photography - Photo 40',
      },
      {
        path: '/Travel small/DSC06537_thumb.jpg',
        fileName: 'DSC06537_thumb.jpg',
        alt: 'Travel Photography - Photo 41',
      },
      {
        path: '/Travel small/DSC06867-EditgbdDF_thumb.jpg',
        fileName: 'DSC06867-EditgbdDF_thumb.jpg',
        alt: 'Travel Photography - Photo 42',
      },
      {
        path: '/Travel small/DSC06920-Edit_thumb.jpg',
        fileName: 'DSC06920-Edit_thumb.jpg',
        alt: 'Travel Photography - Photo 43',
      },
      {
        path: '/Travel small/DSC07086_thumb.jpg',
        fileName: 'DSC07086_thumb.jpg',
        alt: 'Travel Photography - Photo 44',
      },
      {
        path: '/Travel small/DSC08936_thumb.jpg',
        fileName: 'DSC08936_thumb.jpg',
        alt: 'Travel Photography - Photo 45',
      },
      {
        path: '/Travel small/DSC09023_thumb.jpg',
        fileName: 'DSC09023_thumb.jpg',
        alt: 'Travel Photography - Photo 46',
      },
      {
        path: '/Travel small/DSC09103_thumb.jpg',
        fileName: 'DSC09103_thumb.jpg',
        alt: 'Travel Photography - Photo 47',
      },
      {
        path: '/Travel small/DSC09140_thumb.jpg',
        fileName: 'DSC09140_thumb.jpg',
        alt: 'Travel Photography - Photo 48',
      },
      {
        path: '/Travel small/DSC09298_thumb.jpg',
        fileName: 'DSC09298_thumb.jpg',
        alt: 'Travel Photography - Photo 49',
      },
      {
        path: '/Travel small/DSC09786_thumb.jpg',
        fileName: 'DSC09786_thumb.jpg',
        alt: 'Travel Photography - Photo 50',
      },
      {
        path: '/Travel small/DSC09831_thumb.jpg',
        fileName: 'DSC09831_thumb.jpg',
        alt: 'Travel Photography - Photo 51',
      },
      {
        path: '/Travel small/DSC09849_thumb.jpg',
        fileName: 'DSC09849_thumb.jpg',
        alt: 'Travel Photography - Photo 52',
      },
      {
        path: '/Travel small/italy-church-landscape--journey-life-photography_thumb.jpg',
        fileName: 'italy-church-landscape--journey-life-photography_thumb.jpg',
        alt: 'Travel Photography - Photo 53',
      },
      {
        path: '/Travel small/ladscape-nottingham-photographer-child_thumb.jpg',
        fileName: 'ladscape-nottingham-photographer-child_thumb.jpg',
        alt: 'Travel Photography - Photo 54',
      },
      {
        path: '/Travel small/landscape-seaside-nottingham-photographer-travel-photography_thumb.jpg',
        fileName: 'landscape-seaside-nottingham-photographer-travel-photography_thumb.jpg',
        alt: 'Travel Photography - Photo 55',
      },
      {
        path: '/Travel small/laundry-italy-landscape_thumb.jpg',
        fileName: 'laundry-italy-landscape_thumb.jpg',
        alt: 'Travel Photography - Photo 56',
      },
      {
        path: '/Travel small/old-man-portrait-italy_thumb.jpg',
        fileName: 'old-man-portrait-italy_thumb.jpg',
        alt: 'Travel Photography - Photo 57',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-21',
  },

  {
    id: 'sports',
    slug: 'sports',
    title: 'Sports',
    description: 'Dynamic sports and action photography',
    category: 'Sports',
    coverImagePath: '/Sports/Album cover1_thumb.jpg',
    imageCount: 25,
    images: [
      {
        path: '/Sports/441390762_468504128977186_1641526416194860178_n (1)_thumb.jpg',
        fileName: '441390762_468504128977186_1641526416194860178_n (1)_thumb.jpg',
        alt: 'Sports - Photo 1',
      },
      {
        path: '/Sports/Album cover1_thumb.jpg',
        fileName: 'Album cover1_thumb.jpg',
        alt: 'Sports - Photo 2',
      },
      {
        path: '/Sports/DSC00486_thumb.jpg',
        fileName: 'DSC00486_thumb.jpg',
        alt: 'Sports - Photo 3',
      },
      {
        path: '/Sports/DSC00618_thumb.jpg',
        fileName: 'DSC00618_thumb.jpg',
        alt: 'Sports - Photo 4',
      },
      {
        path: '/Sports/DSC01161_thumb.jpg',
        fileName: 'DSC01161_thumb.jpg',
        alt: 'Sports - Photo 5',
      },
      {
        path: '/Sports/DSC01530_thumb.jpg',
        fileName: 'DSC01530_thumb.jpg',
        alt: 'Sports - Photo 6',
      },
      {
        path: '/Sports/DSC01923_thumb.jpg',
        fileName: 'DSC01923_thumb.jpg',
        alt: 'Sports - Photo 7',
      },
      {
        path: '/Sports/DSC01987_thumb.jpg',
        fileName: 'DSC01987_thumb.jpg',
        alt: 'Sports - Photo 8',
      },
      {
        path: '/Sports/DSC02003_thumb.jpg',
        fileName: 'DSC02003_thumb.jpg',
        alt: 'Sports - Photo 9',
      },
      {
        path: '/Sports/DSC02095_thumb.jpg',
        fileName: 'DSC02095_thumb.jpg',
        alt: 'Sports - Photo 10',
      },
      {
        path: '/Sports/DSC02214_thumb.jpg',
        fileName: 'DSC02214_thumb.jpg',
        alt: 'Sports - Photo 11',
      },
      {
        path: '/Sports/DSC03903_thumb.jpg',
        fileName: 'DSC03903_thumb.jpg',
        alt: 'Sports - Photo 12',
      },
      {
        path: '/Sports/DSC04013-Edit_thumb.jpg',
        fileName: 'DSC04013-Edit_thumb.jpg',
        alt: 'Sports - Photo 13',
      },
      {
        path: '/Sports/DSC04293_thumb.jpg',
        fileName: 'DSC04293_thumb.jpg',
        alt: 'Sports - Photo 14',
      },
      {
        path: '/Sports/DSC05753_thumb.jpg',
        fileName: 'DSC05753_thumb.jpg',
        alt: 'Sports - Photo 15',
      },
      {
        path: '/Sports/DSC06003_thumb.jpg',
        fileName: 'DSC06003_thumb.jpg',
        alt: 'Sports - Photo 16',
      },
      {
        path: '/Sports/DSC06105_thumb.jpg',
        fileName: 'DSC06105_thumb.jpg',
        alt: 'Sports - Photo 17',
      },
      {
        path: '/Sports/DSC06318_thumb.jpg',
        fileName: 'DSC06318_thumb.jpg',
        alt: 'Sports - Photo 18',
      },
      {
        path: '/Sports/DSC06335_thumb.jpg',
        fileName: 'DSC06335_thumb.jpg',
        alt: 'Sports - Photo 19',
      },
      {
        path: '/Sports/DSC06392-2_thumb.jpg',
        fileName: 'DSC06392-2_thumb.jpg',
        alt: 'Sports - Photo 20',
      },
      {
        path: '/Sports/DSC06407_thumb.jpg',
        fileName: 'DSC06407_thumb.jpg',
        alt: 'Sports - Photo 21',
      },
      {
        path: '/Sports/DSC06676_thumb.jpg',
        fileName: 'DSC06676_thumb.jpg',
        alt: 'Sports - Photo 22',
      },
      {
        path: '/Sports/DSC07673_thumb.jpg',
        fileName: 'DSC07673_thumb.jpg',
        alt: 'Sports - Photo 23',
      },
      {
        path: '/Sports/dwar_thumb.jpg',
        fileName: 'dwar_thumb.jpg',
        alt: 'Sports - Photo 24',
      },
      {
        path: '/Sports/swdd_thumb.jpg',
        fileName: 'swdd_thumb.jpg',
        alt: 'Sports - Photo 25',
      }
    ],
    isPrivate: false,
    createdAt: '2026-02-21',
  }
];

// Helper to get all albums with proper image URLs
export function getAllAlbums() {
  return albumsData.map(album => ({
    ...album,
    coverImage: album.coverImagePath ? getImageUrl(album.coverImagePath) : '/placeholder-album.jpg',
  }));
}

// Helper to get album by slug
export function getAlbumBySlug(slug: string) {
  return albumsData.find(album => album.slug === slug);
}

// Helper to get album images with full URLs
export function getAlbumImages(albumId: string) {
  const album = albumsData.find(a => a.id === albumId);
  if (!album) return [];

  return album.images.map(img => ({
    ...img,
    url: getImageUrl(img.path),
  }));
}

// ─── Category helpers ───

export function categoryToSlug(category: string): string {
  return category.toLowerCase().replace(/\s+/g, '-');
}

export function slugToCategory(slug: string): string | undefined {
  const categories = getCategories();
  return categories.find(c => categoryToSlug(c) === slug);
}

export interface CategoryInfo {
  name: string;
  slug: string;
  albumCount: number;
  totalPhotos: number;
  coverImage: string;
  albums: ReturnType<typeof getAllAlbums>;
}

export function getCategories(): string[] {
  const cats = new Set<string>();
  albumsData.filter(a => !a.isPrivate).forEach(a => cats.add(a.category));
  return Array.from(cats);
}

export function getCategoryInfo(): CategoryInfo[] {
  const allAlbums = getAllAlbums().filter(a => !a.isPrivate);
  const categoryMap = new Map<string, CategoryInfo>();

  for (const album of allAlbums) {
    const existing = categoryMap.get(album.category);
    if (existing) {
      existing.albumCount++;
      existing.totalPhotos += album.imageCount;
      existing.albums.push(album);
    } else {
      categoryMap.set(album.category, {
        name: album.category,
        slug: categoryToSlug(album.category),
        albumCount: 1,
        totalPhotos: album.imageCount,
        coverImage: album.coverImage,
        albums: [album],
      });
    }
  }

  return Array.from(categoryMap.values());
}

export function getAlbumsByCategory(categorySlug: string) {
  const category = slugToCategory(categorySlug);
  if (!category) return [];
  return getAllAlbums().filter(a => !a.isPrivate && a.category === category);
}
